### ISSUE TITLE
Spawn location selection lets me spawn at wrong location

### ISSUE THREAD

**Issue by bittedanke** [DayZMod/DayZ#101]
4 times I tried to spawn in Chernogorsk, but I spawned 3 at Elektro, 1 time at Cap Galova.
Selecting Balota let me spawn in Komarowo 2 out of 4 times.

List: Spawn selection vs spawn location
Cherno - Elektro
Cherno - Elektro
Cherno - Elektro
Elektro - Elektro
Balota - Komarovo
Balota - Balota
Balota - Komaorvo
Balota - Balota
Cherno - Cap Galova
Elektro - Elektro
Cherno - Elektro
Cherno - Wilderness
Cherno - Elektro

I don't think this is how it was ment to work or else selection is useless.

**Comment by NonovUrbizniz** [comment]
Thanks for your report!

This is because the spawn areas are set by a circular zone. Due to certain restrictions on what is a "safe area" to place a player, and the number of players that can be spawning at the same time on a busy server.

The Devs are working on a solution and may be able to narrow these zones, but testing must be done first.
