### ISSUE TITLE
Request to use 1.8.x.x code in my mod

### ISSUE THREAD

**Issue by KevelTV** [DayZMod/DayZ#137]
Hi,
I would like you to ask for permission to use your code in my mod.

Name of mod is not yet announced(Unofficial name of mod Dayz ADX Podagorsk) and made on map Podagorsk (but will support other map)

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release i do and im willing to backport code/models/sfx/animations to the official if requested.

Understand that im only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

We are agree with the licence conditions.

Sorry for my bad english; English is not primary languages... Im from Russian =)
All the best,
Kevel.

**Comment by AlexAFlorov** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

З.Ы. Название мода?

**Comment by KevelTV** [comment]
"We are agree with the licence conditions."

Название на данный момент не официальное: Dayz ADX Podagorsk
Официально будет примерно, когда допишем мод.

**Comment by Skaronator** [comment]
Please update this issue if you has the final name and close it yourself.
thanks
