### ISSUE TITLE
Usage Request - DayZ Aftermath

### ISSUE THREAD

**Issue by Rossymond** [DayZMod/DayZ#163]
Request for use of extracts from latest DayZ release within DayZ Aftermath 

AmberHelios filled in all the details for me.

I agree to the license conditions.

Many thanks guys.

**Comment by Skaronator** [comment]
You must include all Dayz Credits and (re)create a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You all only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create.

**Comment by Rossymond** [comment]
May I ask does this backport request cover all original content created by us or does it only cover modified code included in the 5 aforementioned PBO files?

**Comment by Skaronator** [comment]
While any original content is solely theirs, we do request a "give and take" type of agreement in such we release all our content in hope they will share some of theirs should we ever request some.
It is not by any means an agreement that we can simply take anything we want from their mod, we will always request in faith that they will be willing to share back to us.

**Comment by Rossymond** [comment]
That sounds more than reasonable to us. Many thanks for your help.

**Comment by Skaronator** [comment]
alright
