### ISSUE TITLE
Request to use DayZ code in my own mod

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#164]
Hi, 
i would like to use DayZ code in my own Submod.
There is no name yet for the mod.

**Comment by Skaronator** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.
Also include the Name of your Mod plz

**Comment by ghost** [comment]
I agree with that. I will provide a name for the mod as soon as there is one. Thank you very much

**Comment by Skaronator** [comment]
kk ty

**Comment by Skaronator** [comment]
Reopend for now, include the name into this issue and close it yourself, ty
