### ISSUE TITLE
Request to use DayZ content and code in DayZ Genesis

### ISSUE THREAD

**Issue by spectrez** [DayZMod/DayZ#165]
i wish to use you're code and content in a mod of my own.

I know im only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

The mod will be named "DayZ Genesis"

**Comment by Skaronator** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by spectrez** [comment]
I am very fine with this, thanks

**Comment by Skaronator** [comment]
alright
