### ISSUE TITLE
Trap trigger loop

### ISSUE THREAD

**Issue by ldy985** [DayZMod/DayZ#169]
There is a infinite loop in the Server_monitor.sqf located in the server pbo
Line 243: while { true } do {

The loop contains no sleep which causes it to run at the fastest speed the server can provide. It will cut server performance (from 50 CPS to 25 CPS) in half before the arma engine limits it.

Change all below Line 243 to: http://pastebin.com/raw.php?i=btCXuDJT

CPS = Calculations per secound

**Comment by icomrade** [comment]
Okay, in a scheduled environment (spawn/exec/execVM) the engine will automatically add a 0.3ms delay between loop iterations. The sleep is redundant, any additional or unnecessary sleep in a spawn will further increase processing time and in high load situations will take far longer than expected to complete or even freeze the loop (sleep/waitUntil is checked every frame per frame).

The 0.3ms delay in a scheduled environment is the same reason why we can have infinite loops as opposed to in a non-scheduled (call for example) environment where max iteration is 10k.

It would be a terrible, terrible, idea to change this loop to a call and add a sleep, DO NOT DO THIS!

**Comment by ldy985** [comment]
It's already a "call" in the official files ?

**Comment by icomrade** [comment]
In 1.8.0.3 it was changed to a spawn. 

```
    // Trap loop
    [] spawn {
```

**Comment by ldy985** [comment]
Hmm, i see. i was looking at Line 266 and 270.
But if the above it true, about it auto adding a 0.3ms delay, can you explain why adding a sleep improves performance from 25 CPS to 50 ?

also when did i suggest changing it to a call ? ("loop to a call")

**Comment by icomrade** [comment]
That was just a note, sorry. :) But I thought it would be worth noting since opening new threads on the server, if you are running multiple instances especially, may severely degrade performance.

How are you counting commands per second? The info I used was from some BIS employees and the code optimization/control structure biki articles.

As an example, there was an issue with the camp spawner on the server long before 1.8.0 release, debugging revealed that the issue was connected to the sleep commands and deletevehicle/createvehiclelocal commands (which does not use the faster array structure of createVehicle, this is why I switched it to setposATL (setPosATL/ASL is ~10x faster than setpos due to the lack of angle and terrain checks) and why it is like this in current build. Long story short the createvehiclelocal/deletevehicle command was so intensive that in a loop with sleeps (increasing or decreasing the time was irrelevant in this case) the time per frame to check the sleep/waituntil was so high that it would never complete. So it was rewritten with out sleeps and with a less intensive command.

The file is fn_bases and you will see that all sleeps in the loop for building/base spawning are commented out.

**Comment by ldy985** [comment]
I see in the fn_bases, i use:
http://www.armaholic.com/page.php?id=21437 (ASM)
to monitor server performance (Yes in arma 2) or this to monitor CPS directly to logs: https://dl.dropboxusercontent.com/u/86516000/fn_ASMtest.fsm?dl=1

I can't explain why, but adding the sleep gave me a noticeable performance increase.

Without sleep:
https://dl.dropboxusercontent.com/u/86516000/ASM%20LOW.JPG

With sleep:
https://dl.dropboxusercontent.com/u/86516000/ASM%20HIGH.JPG

OBJ = count allMissionObjects "All";
MEM = memory used by arma
FPS = Server Side FPS (simulations cycles per sec, same as #monitor 1 when logged in as admin)
PL# = Players on server
AIL = Number of zombies (allmissionobjects "zZombie_Base";)
AIR = number of loop piles (allmissionobjects "WeaponHolder";)

**Comment by R4Z0R49** [comment]
Adding an extra sleep will slow it down more giving more cps. The real question is does that sleep have any other effect if not we gained some performance.

**Comment by icomrade** [comment]
Can you try adding a sleep to each loops (the foreach loop right before }foreach ...; and the last line of the while loop) you may want to do half the sleep time then. If it's not too much to ask.

**Comment by ldy985** [comment]
i have tried some different stuff now.

All sleep values used is "sleep 0.5;"

Sleep last in foreach only: (Low CPS)
https://dl.dropboxusercontent.com/u/86516000/ASM%205ms%20foreach.JPG

Sleep last in while only: (High CPS)
https://dl.dropboxusercontent.com/u/86516000/ASM%205ms%20while.JPG

Sleep both places: (High CPS)
https://dl.dropboxusercontent.com/u/86516000/ASM%205ms%20x2.JPG

Used "[] spawn {" instead of "[] call {" with no sleep: (Low CPS)
https://dl.dropboxusercontent.com/u/86516000/ASM%20spawn.JPG

**Comment by icomrade** [comment]
Thanks for your help. :)

The reason spawning the things in the loop is a bad idea is because spawn need to create a new thread. Every time the loop is run a new thread is created, therefor if there are lots and lots of traps the server will experience exponentially slower performance.

I'll spend some time before the next patch reviewing some of the code in order to improve performance.

**Comment by ldy985** [comment]
Thanks!
