### ISSUE TITLE
Request to use DayZ code in my own mod Dead Nation .

### ISSUE THREAD

**Issue by malakdecaen** [DayZMod/DayZ#170]
Hi , i would like to ask permission for use dayz_code on my mod Dead Nation on Arma 3

You can get more details about the mod here : deadnation.eu
All Arma 2 content have been removed .
Of course i will add in credits files all of you'r credits.

Thanks for you'r reply .

**Comment by Skaronator** [comment]
You must include all Dayz Credits and (re)create a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You all only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create.

**Comment by malakdecaen** [comment]
Hi and thanks to reply ,
I've add all dayz credit to my mod and agreed you'r request .
Thanks

**Comment by Skaronator** [comment]
k ty
