### ISSUE TITLE
Request to use DayZ code in a Arma 3 Mod

### ISSUE THREAD

**Issue by XerxesIV** [DayZMod/DayZ#172]
Hello I was told to come here  to ask permission for use of the dayz_code on my personal project DayZed on Arma 3

Still getting a site together with details
-adding new zed skins
-player skins
to start
The Arma 2 content will not used (mainly ALLinArma) stuff
I Agree to all the terms in the license agreements and per speaking with R4ZOR49

Thanks for your time

Xerxes

**Comment by R4Z0R49** [comment]
You must include all Dayz Credits and (re)create a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You all only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create.

DayZ must not be used within the mod name.

**Comment by XerxesIV** [comment]
I agree with all of the above.
