### ISSUE TITLE
Permission to use DayZ assets in Quarantine

### ISSUE THREAD

**Issue by Purplish** [DayZMod/DayZ#173]
Hi I would like to obtain permission for a new mod called Quarantine

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future releases I make.

I fully understand the limitations of editing only the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx & dayz_comunityassets.

I will seek BIS/Dean Hall's permission to edit any other pbo.

**Comment by Purplish** [comment]
Forgot to mention that I will include all credits.

**Comment by R4Z0R49** [comment]
You must include all Dayz Credits and (re)create a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You all only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create.

DayZ must not be used within the mod name.
