### ISSUE TITLE
Request to use Dayz code in my own mod

### ISSUE THREAD

**Issue by M3RCH4N3RY** [DayZMod/DayZ#175]
I would like permission to use the Dayz 1.8.X.X code in my own mod. I agree to the terms and conditions and will make a issue post every three months requesting permission to use the files in my future releases.

I will also give all credit to the original creators.

I agreed to only edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets and no others.

The name of the mod is going to be DayZ Lian Yu

**Comment by R4Z0R49** [comment]
You must include all Dayz Credits and (re)create a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You all only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create.

DayZ must not be used within the mod name.
