### ISSUE TITLE
Flies Sound Not Dissapering when body is buried

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#187]
Flies Sound Not Dissapering when body is buried

not sure if this is a bug but if its not in the game it should be

**Comment by R4Z0R49** [comment]
They should be part of the server cleanup system.

**Comment by R4Z0R49** [comment]
Correction this has been a long term issue. one of the reasons we remove it to start with.

**Comment by facoptere** [comment]
Flies sound is half-networked.
New incoming players won't hear it if they came in after it spawned. So you request the new gameclient to spawn it
Then connected players will ear it very loud because it's repeated several times. Best solution is to remove it and recreate it periodically. However day sound should be removed as soon as the body is gone.

**Comment by R4Z0R49** [comment]
Closing this for now. They have been removed for 1.8.2
