### ISSUE TITLE
Things not spawning and Battleye script.txt

### ISSUE THREAD

**Issue by Razor14150** [DayZMod/DayZ#20]
Hello my server is hosted through dayz.st and recently they updated to the 1.7.7 patch and to start things off I had to comment out/remove my entire script.txt from battleye just to be able to join it. It started with #112 so I went and commented out lines 112 and 115, then it jumped to #110 then #108 ect up to I think 100 then I just commented out a bunch and got a script restriction 66... so I just deleted it all so people could get on last night ( as I had to go to work)

Now I come home to learn from my playerbase that loot and zeds are not spawning... Its with regret that I cant downgrade to 1.7.6.1 again till this problem is solved.

**Comment by icomrade** [comment]
Keep in mind that if you see a comment in a filter you need to +1 to the restriction number. The filters start at 0 not 1, so #112 is line #113 if there are no comments before. I'm assuming you used the latest battleye filters from here: https://github.com/DayZMod/Battleye-Filters

We have had reports of loot and zed spawns being wacky and are looking into ways to make them more reliable.

**Comment by facoptere** [comment]
I assume your are using current scripts.txt from the URL mentioned above.
For now, scripts.txt ban for very few rules, most of them begin with "1", so you can't be kicked by this filter.

**Comment by R4Z0R49** [comment]
Remove all filters and test the server.

**Comment by ExcelsiorDDZ** [comment]
commented lines are also not counted.

so // lines will cause the numbers to skew a lot.

**Comment by fgw-** [comment]
on a sidenote:

might be a good idea to remove all commentlines and empty lines from filter files in order to easy identify the line in question. may be this can be done at https://github.com/DayZMod/Battleye-Filters, so all people will use the same files, thus the same error numbers. you can even put a commentline in the first line of each file, to make the errornumber directly represent the linenumber in the file. have not yet tried this, but from logic this should work ...
