### ISSUE TITLE
Zombie Aggro broken

### ISSUE THREAD

**Issue by Nekrophis** [DayZMod/DayZ#207]
Ok, so I understand that the game is entirely based around zombies, but I keep running into problems involving their random aggro. Zombies will randomly aggro from distances that I wouldn't think possible and when out of sight. Another problem is that my friend full sprinted right past a zombie and the zombie keeps shambling by, but me, the one crouching 100 meters away gets aggro'd by that same zombie at the same time. The zombie's attack animation is also broken when you consider that dodging a zombie attack is now impossible because the actual damage now takes place before the animation. This means that dodging attacks and trying to run from zombies is not an option. The only way to get rid of these zombies without taking damage is to run into a bush or through a building.

**Comment by R4Z0R49** [comment]
There really isn't much random about it if your to visible the zeds will see you. if you make too much noise the Zeds will hear you. Max target range is 200 meters so they can hear and see upto 200 meters.
Zeds in DayZ are not zombies they are infected humans meaning they can technically see and hear everything the players can. Now the issue with your friend might be a silly case of his client crashed script wise it does happen. The attack animation we are aware off and should be fixed in the next build.

Thanks
