### ISSUE TITLE
ItemNails and equip_nails

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#216]
To build fences you need "ItemNails" (descr: Box of Nails). Loot tables only spawn "equip_nails" (descr; A small box of 4 inch nails). 

So building fences is not possible for players or non-admins.

"ItemNails" whatsoever cannot be used to upgrade Stashes.

.

**Comment by R4Z0R49** [comment]
Yea that sucks ill get that fixed. For now add the nails to chopper sites and drops sites or maybe infected camps

**Comment by R4Z0R49** [comment]
fixed

**Comment by ghost** [comment]
I just added ItemNails to my loot tables with the same values as equip_nails for a quickfix

Where do I change the requirements for building the fences, so I can get rid of the ItemNails there instead of flooding my loot spawns with both kind of nails. ;)

**Comment by R4Z0R49** [comment]
If its a mission side file might be worth showing others how to do this as well.

**Comment by ghost** [comment]
No I changed this in the loot tables in dayz_code,pbo so this is just a quickfix for me. There are a lot of tutorials on how to put the loot tables to the mission file, but on this particular server, I didn´t bother to pull it mission-side, yet.

Again, where do I set the required items for building/updating the fences, so I can fix it for myself, instead of waiting for 1.8.3?

**Comment by R4Z0R49** [comment]
Its config files i don't think you can change them from the mission. buildings/config

**Comment by ghost** [comment]
Nah, I don´t want to change it in the mission file. I have full access to all my DayZ files, as I run a dedicated server,

When I go to 
@DayZ\Addons\dayz_code\Configs\CfgVehicles\Buildings

there is no line, where I can change the required items for building the stuff. I guess it will be some kind of array where I just need to replace the "ItemNails" to "equip_nails", right? But where can I find that?

**Comment by R4Z0R49** [comment]
@DayZ\Addons\dayz_buildings\config.cpp

**Comment by ghost** [comment]
Ah. _facepalm_

Fixed and works like charm.

Thanks for your support!

**Comment by kichilron** [comment]
Are you the only one playing that server? Ic not, you will run into issues with the files no being signed properly anymore.

And if you set verifySignatures to 0, you will have issues with people joining your server with old versions.

**Comment by ghost** [comment]
yeah sure, you´re right, I´m testing on my test server @port 2324, with verifySignatures=0

I will pull my loot table server side tonight, so I will be able to adjust the loot tables mission side. I guess the fix in dayz_buildings.pbo will have to wait, unless you provide me with your private key to sign the pbo correctly. :))))

**Comment by kichilron** [comment]
Even then they wouldn't have the correct signed files, as they differ from our version and noone could join.

You should be able to change buildingloot in themission, though.

**Comment by ghost** [comment]
Yep. I changed the stuff on my test server just for lolz and figuring it out.

I`m pulling the loot tables mission side right now, to apply the "equip_nails" and "ItemNails" to it.

Still the required items for building fences are in @DayZ\Addons\dayz_buildings\config.cpp which condemns me to waiting for a fix by you guys.

**Comment by kichilron** [comment]
There are two different versions of the nail, both of which should be working fine.

We will be making sure to double-check which ones we're using and that those are going to be included in the Loot-Table. But theoretically it should be all fixed in our internal builds.

**Comment by ghost** [comment]
equip_nails = upgrading stashes
ItemNails = building fences

Original loot-tables contain equip_nails only.

**Comment by R4Z0R49** [comment]
Yea this has been resolved. Thanks

**Comment by cmkb3** [comment]
This can be temporarily fixed by calling an edited fn_upgardeBuilding.sqf in the mission file. I recently lost my code, but the general idea is such:

immediately after the array _partsRequired is initiated and loaded from the config, check if "ItemNails" is in the array, and if it is replace it with "equip_nails". This will let players upgrade the fences with the nails currently in the loot table. Only issue with this is that disassembling the fences still returns ItemNails and a pebble or some such.

_containsItemNails = "ItemNails" in _partsRequired;
if(_containsItemNails) then {
_tmpIndex = _partsRequired find "ItemNails";
_partsRequired set [_tmpIndex, "equip_nails"];
}

replacing variable names where appropriate

edit: this only works if there is only one instance of ItemNails in the _partsRequired array; change to a for loop if necessary but I'm pretty sure all the upgrades require no more than 1 set of nails
