### ISSUE TITLE
Thunderous bells

### ISSUE THREAD

**Issue by lWmPl** [DayZMod/DayZ#258]
In 1.8.3 has appeared some sound glitch: watchtower bells ring throughout whole Chernarus!

**Comment by Detoeni** [comment]
its a bit odd, heard a bell ring at prud, then heard the bell at novy a second or so latter. i was half way between them, and far enough away from grish to be sure the first one was not from there.

**Comment by R4Z0R49** [comment]
Yea we think we have found the issue we are just waiting for someone to confirm.

Our fire was incorrectly set
-   simulation = "church";
-   simulation="fire";

So any place theres fire you also got church bells.

**Comment by Wraithe** [comment]
I can confirm the bells thing happening. I was on USA435, and a player was complaining about it, I asked him, as I wasn't hearing anything. Then about an hour later, rolling tolls of multiple bells occurring seemingly randomly, with it happening for multiple players at the same time.
Since then, I've also heard it on my server, HauntedDayZ.
The fire thing sounds plausible, as I've been in area with fires when it's happened for only me.

**Comment by R4Z0R49** [comment]
Fixed.

**Comment by LinusLeonard** [comment]
Could you direct me to the commit that fixed this? I can't seem to find the issue-commit-connection.

**Comment by kichilron** [comment]
The DayZ Mod Repository was private / invisible for the longest time and only recently switched to public again.
You will not be able to see in any case.
