### ISSUE TITLE
Dayz 1.8.3 logging in infected

### ISSUE THREAD

**Issue by Borges80** [DayZMod/DayZ#304]
This has happened to me multiple times whereas I'll log out then log back in 5-10 minutes later (or server restart) and will log in infected without first contracting sepsis. Either that, or the sepsis message does not always show up. It did not show up in center of screen or left hand corner at all and I logged out and back in 5 minutes later and was insta-infected. Happens rather often.

**Comment by R4Z0R49** [comment]
Did you have sepsis before you logged out?

**Comment by Borges80** [comment]
Nope. Without first contracting sepsis. I was hit a few times by zombies but did not receive the message.  Was playing fine for probably an hour until the server restarted, and logged right back in but infected.

**Comment by KPanicEKS** [comment]
I think the problem is that the sepsis message has been moved to side chat
when it used to be in the center of the screen. I would say either put an
indicator on your health droplet or move the message back to the center of
the screen. It's hard to see a sepsis message when it's mixed in with all
the blabber on side chat.

**Comment by Borges80** [comment]
This isn't the problem. I always notice when I contract sepsis on the left hand side and I can tell you I don't miss it. I've been playing for 2 years and always look out for it every time I get hit by a zombie, plus it's easy to see as it's white text mixed in with blue. It didn't appear at all period. 

I'm thinking 
1. Upon getting hit at one point, the player contracts sepsis but never received the message due to a bug and does not execute the 15 minute timer. Logging out then logging back in executes infection after a recheck. So timer/message bug?
2. There's a bug upon login that wrongly reads the players data upon logout after receiving damage from a zombie and reads the player as infected and executes.

Location of the sepsis message, or having an indicator on the health droplet doesn't make a difference if the server is not executing the sepsis warning/timer at all, which may be the problem. It would explain why only upon logging out triggers the infection. Your player has sepsis but does not trigger infection because it's in a delayed mode (no timer) until logout which then rechecks the players status (has sepsis) and then boom, why am I infected? Just my thoughts.

**Comment by Lukethero** [comment]
Sometimes if you log out with a zombie attacking you you will log back in either bleeding or with infection. Most likely your problem though is if you log out with sepsis you automatically log back in with infection.

**Comment by Borges80** [comment]
Yep as I stated above. The problem is that you're not always notified of contracting sepsis, so you never bother wiping and never get infected before logging out cause there's no timer enabled. Pretty annoying when you have no way of curing yourself in time when you login.

**Comment by bchawke** [comment]
I agree with M0tzilla about moving the sepsis warning to the center of the screen.  It's just far to easy to miss with all the chat, server, and death messages scrolling there.

**Comment by R4Z0R49** [comment]
I see no real issue here with the sepsis however the notification system needs some work. if your being attacked from a zed and you know your going to logout after the encounter use the wipe your 100% save that way. They should always be stored by the player

The problem with using it CutText they don't overlap or scroll so they can be missed even more if something else pops up first. TitleText might help but that just overlap everything on the screen so if you get two msgs about something they overlap and you cant read them. 

I'll take a look at a better notification system, But this would have to be created.
