### ISSUE TITLE
1.8.3.a216b06 - adding item to full back pack makes it vanish sort of

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#309]
only this time I found where it went.. directly behind me but 30 m's away.
Luckily it was a white water bottle which shows up quite well in dark wood land.
Not sure if it can be fixed by reducing the range to one where folks can more easily find the dropped item

**Comment by R4Z0R49** [comment]
This is a very old issue. Has a lot to do with how arma works on getting and adding loot. ill see if i can make time to look over this.

**Comment by Detoeni** [comment]
Had another go at this and what happened is not reproducible, ignore it for now and I'll do some more testing and see if I can nail where these things are popping off to

**Comment by bchawke** [comment]
Haha wow, yeah this has been an issue since the BEGINNING!  I've actually found this issue to become a helpful bug as you can delete unwanted items without leaving trash on the ground (I'll put tin cans from eaten food in a full backpack so other players can't track my movement).  I do find it really interesting though that SOMETIMES it will spit the item out on the ground next to you rather than delete it.  Perhaps it always spits it out on the ground but usually ends up below the ground or something?

**Comment by R4Z0R49** [comment]
Take magazine is an arma system i have already started to remove this system but i keep running out of time so i doudt it will be in this next version.
