### ISSUE TITLE
1.8.4.1 losing humanity when killing camo clothed players

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#357]
According to the changelog you don't lose humanity if you kill a camo clothed player (camo, soldier or ghillie). In fact you do lose humanity no matter what clothes a hero/survivor has on.

**Comment by HeroSmurf** [comment]
<b>Works for us on 434 1.8.4.1       hmmmm</b>
What skin were they in? 
Pistol? Maybe related? : I noticed pistol shots seem to march to their own damage drummer

I tested this on kilchron's server before release but just to be sure I took a humanity hit on Vanilla 434 2-3 days ago to be super sure...

<b>My tests were...</b>
I've killed 3 skinned Survivors without a loss. 
I tested this on 434 using 1.8.4.1 with the proper results. 

me positive 55 humanity
friend positive 180 humanity

In a skin(me) shot a survivor (friend) lost 1944 humanity (ouch!)
Logged out. Logged back in. Friend respawns. 
As a survivor(me) shot a skin (same friend in now in Ghillie) no loss. Yay!

We did not derp around exchanging shots etc (did not trigger _canHitFree). 

In the original snippet I sent (PasteBin has since expired) https://github.com/DayZMod/DayZ/issues/316 I pulled "_model" into the sqf but that was deemed unnecessary but folks who understand better than I do what variables lie where when. 

If there is a possible culprit I would look for _model not being consistantly read/passed in the fn_damageHandler but that's all I can think of. I was concerned about that but still seems to work. 

Would it be a good idea just to add this to line 21?
"_model = (typeOf player)" 

Wish I could nail it down better for you. Hope if there is a bug it's repeatable and fixable. 
Let me know if you can repeat the behavior.

**Comment by VidKo** [comment]
He was in soldier clothing and was shot by a M14. The shooter was in ghillie.

**Comment by HeroSmurf** [comment]
Soldier1_DZ might be the wrong skin. Base class maybe?

Would be best to just grab _model above the lookup. 

Looks like skin_soldier1_dz is correct though. 
Or can we add the whole list instead?

 (_model in ["Sniper1_DZ","Soldier1_DZ","Camo1_DZ","Skin_Soldier1_DZ","RusSoldierHeadset_DZ","RusSoldierWinter_DZ","RusSoldierWoodwarrior_DZ","RusCommander_DZ","RusSoldierLight_DZ","HalfGhillie_DZ","RusSpecOps_DZ","RusOfficer_DZ","RusSoldierCasual_DZ","JoggingSuit_DZ","CivWorker_DZ","CivLeatherLeisure_DZ","CivLeatherLeisure2_DZ","CivDoctor_DZ","CivCasualDoctor_DZ","CivPress_DZ","CivCasualCheck_DZ","CivSuit_DZ","CivPressLeather_DZ","CivPilotSuit_DZ","CivPoliceUniform_DZ","CivPriest_DZ","CivLeisureBlue_DZ","CivLeisureGrey_DZ","CivLeisureBrown_DZ","CivRocker1_DZ","CivRocker2_DZ","CivTeacher_DZ","CivRusWoodland_DZ","CivRusWoodland2_DZ","CivCasualCheck2_DZ","CivWorkerOverall_DZ","CivLeisureVest_DZ","CivRedWorkerOverall_DZ","SoldierWoodwarriorCap_DZ","SoldierWoodwarrior_DZ","SoldierWoodwarriorHat_DZ","SoldierCasualShirt_DZ","WoodWarriorIndi_DZ","UNOfficer_DZ","CamoFaceCover_DZ","LeasureKevlar_DZ"]) ;

I cherry picked from this crazy long list. 

Also the half ghillie should result in humanity loss; but only if you shoot him from the waist down :P

**Comment by HeroSmurf** [comment]
K. Can you test it again? :P

**Comment by thcNox** [comment]
I was the one who shot the soldier. Don't have access to a test server where I can test this freely and playing on Dayz Europa I currently don't have direct access to someone with soldier clothing. If I come across somebody though I'll keep you updated. Also I'd like to clarify that there's no mistake on our end. I got a clean kill on a lone soldier guy and I definitely lost humanity, about 1900. went from 90 to about -1840

**Comment by Veltro-pm** [comment]
Am I looking at the right code?branch:Development DayZ/SQF/dayz_code/compile/fn_damageHandler.sqf
_accidentalMurder = (_model in ["Sniper1_DZ","Soldier1_DZ","Camo1_DZ","Skin_Soldier1_DZ"]);

_model is undefined here.

**Comment by MercianUK** [comment]
used hatchet on survivor, one shot kill, Survior was in Soldier Clothing, took around 1900 humanity from me

**Comment by HeroSmurf** [comment]
@ILoveBeans Your exact message is already suggested. Scroll up. 

A safe update/Solution would be to add "_model = (typeOf player)" above the _model. 

@kichilron is already on it

**Comment by kichilron** [comment]
70f3d19

Should be fixed now. Was just missing the Variable, thank you for pointing it out.

**Comment by vinyljunkie** [comment]
Thanks kichilron. Question: Can I add this fix to the dayz_code.pbo on the server and it will work? Or does it have to be added to the clients aswell, i.e wait for the 1.8.5 update?

Thanks

**Comment by R4Z0R49** [comment]
Client fix.
