### ISSUE TITLE
1.8.4.1 Matchbox Increase

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#364]
Match box match count is too low. Temp system is great as it is, and keeps you on your toes to take good care of your character. The problem is, when you need to stop to light a fire to warm up, it stings because you are using one of your 5 strands of life. Matches are really important and a valuable resource that if you run out of, you are screwed to starvation. To account for the new use of matches increase the amount in a box to arround 7-10. In summary, it is a good thing to need to care for yourself, but a little to costly to do so.

**Comment by KPanicEKS** [comment]
I like the fact that matches are a low value but I thought the mechanic was
suppose to work much  like the knife. Where you could use it many times but
with every use there is a chance of having it switch to a matchbox with
only 5 left.  It seems like all matchboxes have 5 uses now by default.

Since we are on the subject of fire starting I do like the idea of being
able to craft a fire bow. 3 wood, knife and string.
http://youtu.be/F95akZGZB18

Of course make its use not 100% guaranteed to start a fire and have it take
a good deal of calories to use with a chance of breaking. (new string to
fix)

**Comment by R4Z0R49** [comment]
The match system is meant to be like the knife it was changed with 1.8.3 unsure why. During the weekend ill change it back.

**Comment by Detoeni** [comment]
It got changed when recombine matches got added to faco's 1.8.3 test server. Never mentioned it as I thought it was intended...

**Comment by R4Z0R49** [comment]
It wasn't the match system should have stayed as it was with the orignal item then a random chance to drop the player to the last 5 match's but of well ill correct it.

**Comment by R4Z0R49** [comment]
https://github.com/DayZMod/DayZ/commit/bf7e2a675896908234f605c2bf0e0128a0566902

Updated back to 1.8.2 system.
