### ISSUE TITLE
failed to disable trash / dayz_Trash = 0; not working anymore

### ISSUE THREAD

**Issue by fgw-** [DayZMod/DayZ#372]
dayz_Trash = 0; 

in variables.sqf seems not to work anymore!

after looking at it i could find dayz_Trash is used in stream_locationCheck.sqf:

_rubbish1 = dayz_Trash == 1;

not sure if this syntax is correct anyway i could not find a call to stream_locationCheck.sqf anywhere! so if this script is not get called, dayz_Trash is obviously not used at all!

may be there is something overlooked in this release?

is there another way to disable trash?

**Comment by R4Z0R49** [comment]
I'll check this out when I have a few mins to spare but I beleave it was changed because the objects are no longer global they spawn only local to the client. That var was added back when it was a networked system slowing everyone down due to global objects spawning.

So really there should be no need to add that var anymore and if players are still having issues they may need to look at the arma 2 recommended specs (not min specs)
