### ISSUE TITLE
1.8.4.1 Gate Issues

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#375]
1. Gates can be built to the level where a ladder is made and you can hop right over someone's wall. A proximity of no build arround someone else's walls needs to be added or wall hopping and stealing loot is going to be happening left and right. Had a few friends who had loads of shit stolen from their highly secure base just because someone had a few nails some stone and an axe.
2. TURN AWAY IF YOU DO NOT HAVE SELF CONTROLL. Currently anybody can upgrade a wall made, even one mad by someone else. Once the wall is upgraded, the person who upgraded it can now disassemble it. Big problem here and NEEDS to be fixed before the next patch comes arround. Now no one go running arround disassembling walls on your servers.

**Comment by HeroSmurf** [comment]
Hey good catch on issue 2)!

I guess I'll be making my way over to your Zelenorsk area base tonight Luke :ghost:

**Comment by Lukethero** [comment]
Shhhhhh it's secret... And try it knight... Got my gremlins on gaurd duty 24/7

**Comment by R4Z0R49** [comment]
The 2nd one i now about already should be an easy fix the first however im not sure about the best way to limit but ill look into it

**Comment by Lukethero** [comment]
Just add proximity building block like the current buildings already have @R4Z0R49 . Probably harder than that, but probably the easiest fix.

**Comment by thcNox** [comment]
Would that not make it so that clan bases would have to be be built by one character?

**Comment by Lukethero** [comment]
@thcNox Yes that would be what would happen. The building part is not what takes that much time though, more the gathering the supplies.

**Comment by R4Z0R49** [comment]
two has been fixed and we still allow anyone to upgrade.

**Comment by thcNox** [comment]
How come the gates aren't placed straight up vertically like the walls? It's like  the walls are using the local axis instead of world.  This makes it a bit troublesome to line them up with the walls like seen in this screenshot: https://dl.dropboxusercontent.com/u/19031182/2015-05-02_00001.jpg

Also they cannot be disassembled but I believe this is already been reported. Anyway great work on this so far I love the new base building, as ex-epoch player I was concerned about base building being introduced in vanilla but this has been done perfectly, it still feels true to "vanilla"
