### ISSUE TITLE
Dead body disappear after 20 minutes

### ISSUE THREAD

**Issue by endreu1** [DayZMod/DayZ#383]
Tested not only by my self, but by other players who always play on  a server.
The dead body will disappear after 20 minutes if no one is near. I died in zelenogorsk, spawned in kamenka. walked by foot to the place where should be a body, but only what i see is blood on grass.
Can this be some how fixed? Some time it's annoying + i hate to lose all my gear on a death.
THX.

**Comment by KPanicEKS** [comment]
someone probably looted and hid you body.

If I may add, (and the forum is probably a better place to discuss this
but... ) it would be nice to see a mechanic added that locked your player
from gearing your old dead body. Dayz is a survival game and it should be
about getting resources to do so, one of the factors that make this game so
great is the permadeath aspect it introduced; but sadly I find that players
most players simply go back to their bodies rather than gearing back up.
Hopefully once the study body / journal counter is implemented maybe there
could be a something else added that would encourage players to hiding the
bodies in effort to discourage players from running up to their dead bodies
to regear.

my thoughts on this are probably not very popular but a huge aspect of this
game is lost when players can regear off their dead bodies so easily.

**Comment by R4Z0R49** [comment]
Its part of the cleanup system its not new.
