### ISSUE TITLE
tripwire traps not working

### ISSUE THREAD

**Issue by Jbird206** [DayZMod/DayZ#429]
one time usage or, grenade tripwires randomly going off. not buildable on roads as well

**Comment by R4Z0R49** [comment]
I need to know witch trip wires so i don't waste an hour going over them all

**Comment by Detoeni** [comment]
Is there a safety time out after placing these?
tested crafting/placing smoke/flare/grenade as well as spawning ready made.
Results were very odd/inconstant.
Had one flare start a second after placing - player/z had not crossed wire.
some grenade tripwires seem to go off after a delay (no dead z found).
had one smoke that was triggered by z but about 7 that did not.
had three smoke that I am not sure if a tripwire grenade triggered or z
None were seen to be triggered by player/owner - is this by design?

**Comment by Jbird206** [comment]
Yes, I've noticed the same thing.  Got a sour response from Carl so I didn't elaborate.

**Comment by R4Z0R49** [comment]
Hum I only asked which ones you had issues with.

**Comment by R4Z0R49** [comment]
I'll go over all the traps at the weekend see if i can see whats going on.

**Comment by Jbird206** [comment]
Thanks man. Just trying to help.

**Comment by CoftSock** [comment]
there is just desync / delay (30 seconds) in them going off. tried the grenade and flare one on a server with 0 players on and they did eventually go off but did have a delay

**Comment by Detoeni** [comment]
all the traps that I placed for this test are still in place from 16 days ago, should they have been cleaned up by now?

**Comment by Jbird206** [comment]
That'd be a server setting I believe.

**Comment by R4Z0R49** [comment]
ill look into that one.

**Comment by R4Z0R49** [comment]
should be fixed.
