### ISSUE TITLE
[Suggestion] Some new special place for Cherno

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#431]
Hallo again,

so this is a little idea to bring a new place into Chernarus. Since I'm playing DayZ I'm missing a nuclear area of the country (maybe because I often relate Cherno to Chernobyl). This sounds like a giant task but it isnt. Actually you would only need one item and a small modified place on the map (I would suggest the free fields around the Prud above Stary Sobor). 

At this place should be a small industry complex with a huge destroyed building and some smaller industry buildings around it. Maybe some smoke above the building and some military cars, tents and generators around it. The area is surrounded by military fences and signs to warn people. This could be done with Arma 2's 3d editor - I already designed something like that years ago. This place would be the reactor that has been "destroyed after the virus started".  When a player gets close to the area the radiation takes effect on him (visible with some post-process effects) and damages players until they die after a while (depending on distance and time). The new Geiger counter tells a player whether there is radiation around him with this typical Geiger sound (https://www.youtube.com/watch?v=upPiJ9vOYiY). 

So, why should players go to a place where they can only die? Because the military left a huge amount of equipment there - maybe 4-5 spawns for vehicles like helis and cars and a lot other equip in the tents. Repairing the vehicles and getting the equip gets difficult because players can only stay for a short while in the area. 

I know this sounds like a giant task but it isnt. One new item with skin and sound that gets louder when it gets closer to the nuclear point. Some objects on the map and a maybe a trigger (or a scripted solution) for detecting players in the area and to affect them using the new radition variable and the pain effects. 

Tell me what you think about it, I have talked to many people about the idea and most said that this would give the mod something really cool and special and it perfectly fits into Chernarus!

Regards!

**Comment by ericandersen** [comment]
I love your description. If done right it would be a great addition. 

My only suggestion would be let's put it in a non populated part of the map; like Gvodzno or up by Pedoba (spelling?) Dam. In this way it would be a mid point on that long trek between NEAF and Devils. 
. 
The mid-west of the map (Stary, Old Fields, Grishino, NWAF) have enough interest points and Prud (as how the area is laid out geographically and surrounding towns) doesn't make sense as an industrial plant. If you were the Mayor of Chenarus you'd say; nuclear you say? oh damn, let's put it near the dam. 

Also it would make sense that the dam is FOR SOMETHING up there; 
Possibly for power or to cool down the reactors quaid. 

If it doesn't get done you've made me happy just thinking about it. 

If you're looking for a team to build a proof of concept and code the new "radation poisoning" I'm happy to join in and I know Motzilla can help with the map/small models. 

My approach (unless you and I are the only interested parties) would be let's build it, film it, and then let R4Z0R and team decide if it's worthy. Here if you need/want my help.

**Comment by ghost** [comment]
The radiation damage could be done quite easily by a trigger. There is a protective dome script somewhere, that kills every player after several timed warnings. This could be modified to deal like 1 damage per second, when entering the area. But there should be means of protecting yourself against the radiation. Hazmat suits... there should be models for those around.

**Comment by ghost** [comment]
> The mid-west of the map (Stary, Old Fields, Grishino, NWAF) have enough interest points and Prud (as how the area is laid out geographically and surrounding towns) doesn't make sense as an industrial plant.

Good point! :+1: but we definitly need a free place to build this thing. Maybe it could look like this: http://media.moddb.com/cache/images/mods/1/22/21598/thumb_620x2000/ArmA2OA_2012-11-29_17-55-46-80.jpg

> Hazmat suits... there should be models for those around.

Nice idea but first lets focus on the core part of the idea and then we can add features like that. Maybe some suits like this: http://kodabar-dayz-daizy-single-player-forum.1084782.n5.nabble.com/file/n1807/arma2oa_2013-02-11_12-48-18-041.png

> If you're looking for a team to build a proof of concept and code the new "radation poisoning" I'm happy to join in and I know Motzilla can help with the map/small models. 

That would be awesome! Lets wait for R4ZOR's feedback

**Comment by R4Z0R49** [comment]
i don't know not sure about this.

But nice info 7rust.

**Comment by ghost** [comment]
Take your time to think about it! It should'nt be too large. Maybe we can talk on teamspeak about it!

**Comment by thcNox** [comment]
Sounds like a cool idea, I'm all for adding some new spice to the chernarus map. Just that you would have take great care and not make the "spice" too overpowering. For example I do not think you'd want a huge complex that could rival NW airfield or cherno. Also the amount of militiary loot added would have to be really balanced, if you add more loot than NW airfield has then suddenly this new complex is what the end game would all be about which I think is not what you want. You want to this new complex to balance the map not just create a new huge hot spot.

Also another concern is that the requirement of hazmat suits etc to loot this complex would really play well into the hands of the already established veteran squads so that they would have even easier access to high tier loot while the average bambi guy is just going to end up getting wrecked even harder.

That said, if you can balance it, I can see it be a cool addition to the game but it will not be a an easy task.

**Comment by ghost** [comment]
> then suddenly this new complex is what the end game would all be about which I think is not what you want. 

No no, definitly not! But if we want to rebalance the map we need a new spot that is at least so powerful like the airfield and Stary and we need to remember that this new area is more dangerous than most other areas of the map because of the radtiation and so it must be worthwhile to visit it.

But we can decide, do we want to rebalance the map with some new loot spots or do we only want to add a new special place. (btw: http://i.imgur.com/Aua1UMv.jpg)

I guess a little conversation on Teamspeak would help us to exchange our ideas!

**Comment by kichilron** [comment]
Alright, so here are my thoughts about this. Don't get me wrong, I love the general idea of it and I would love it to come true, but here are my concerns with it:
- Does this really fit the setting? We're looking at a Zombie / Infected setting here, but that doesn't necessarily mean a wasteland or nuclear area would fit.
- You're going to run into **massive** problems with the playerbase, because they're simply not used to it. And because we have no area on the map where people have not been it's hard to realise. If we were to go for a new map it would easyily be implemented, but the reality is that most of the playerbase won't even read the patchnotes. Thus, if we were to implement such a nuclear area, there'd be a lot of moaning.
- What about people's bases? As long as it's going to be on the map someone will have a base in the area of the nuclear fallout.

I have a few more concerns which make me really be torn in two over this. On one hand I would love to see this coming, but on the other hand I really don't think it is possible at the moment.

**Comment by thcNox** [comment]
All valid points  kichilron,　however if you have to take into consideration stuff like peoples bases etc or that people won't read the change log I think there's a real risk of being too locked down and not being able to implement new content or moving forward in any direction really which will lead to the mod stagnating and eventually die out. 

I know the guys in my community would not be too butt hurt about losing a stash or a tent to these kind of changes, rather I'd think they'd gladly give them up in order to keep the mod alive. Perhaps you can offer people who will be affected by this a move of their stuff on a per server basis?

My main concern that I share with you though it that it has to fit setting of the map. Getting this project to be a valued and balanced addition to the map while still fitting the Chernarus theme is going to be the hardest me thinks.

**Comment by ghost** [comment]
@kichilron I can fully understand your points. 

> Does this really fit the setting? We're looking at a Zombie / Infected setting here,

In my oppinion it does. Just think about Chernobyl which looks pretty similiar to Chernarussland (e.g. http://a.abcnews.com/images/US/HT_chernobyl_trees_building_nt_130827_16x9_992.jpg). To bring it into the world of DayZ/Cherno you could say: The reactor has been destroyed after the engineers got infected by the "virus" and after it exploded the military decided to evacuate the area. As I already said before, <b>not too much</b>. This should be an addition to the map and the size off the area around the reactor should be maximum 200-300 meters.

> playerbase won't even read the patchnotes.

But thats not what DayZ is about - DayZ means surviving in a unknown lost world and maybe also exploring special places and not reading the changelogs.

e.g.: http://steamcommunity.com/sharedfiles/filedetails/?id=439913693

**Comment by CoftSock** [comment]
industrial buildings you'd be able to do but the nuclear reactors where made for tavianna map so you will need permission right? and the files would then need to be included with DayzMod files

**Comment by ghost** [comment]
I have taken a look at Taviana and it provides some really nice buildings. I added some screenshots of the area that looks similar to a reactor or some energie station. In my oppionion <b>the complex is a way to big</b> but looks awesome! I imagine some smaller reactor that fits into the world of Chernarus. What do you think guys?

http://images.akamai.steamusercontent.com/ugc/720918374238912615/9A6B6E059F4F6682ED493FD8605FD55E4D17D3E6/

http://images.akamai.steamusercontent.com/ugc/720918374238912068/13EA3910734FE2689DB3BB7518F1800787575339/

http://images.akamai.steamusercontent.com/ugc/720918374238909714/24F9353B83D8D0ACE43EB0BD7F80A3C443F01D28/

http://images.akamai.steamusercontent.com/ugc/720918374238909094/0DC57F96862002BD6AC21515D057A0A6D571884F/

**Comment by ghost** [comment]
Some example Geigercounter item:
![geigercounter_obj_entwurf](http://i.imgur.com/e64WIra.png)

**Comment by KPanicEKS** [comment]
if I remember correctly from my Taviana dayz that complex was buggy as
hell. Lots of wall you could clip into as a player, it was a mess.

**Comment by R4Z0R49** [comment]
Spoke with the op about this a contaminated area is fine i don't see any reasons we cant look into this however reactors are a no go i wont be adding any sort of reactor.

**Comment by Lukethero** [comment]
@7rust I think this is a wonderful idea. After a while of playing, you realize how boring the map gets and how the balance of it is off. Most people just either stick on coast, or run up to NWAF then to Stary or stary to NWAF. This would kill 2 birds with one stone by spicing up the map and bringing a POI to the east. This complex should also have some exclusive spawns or increased spawns to make sure people go to it instead of just going to NWAF anyways. Maybe increased lock spawns some of the new interesting items being added.

Similarly, I think the addition of the compound to NWAF was not well thought out. It just cements the the idea of go to NWAF for gear. This structure allows players to be decked out in 3 minutes with little effort. Why not spread the military gear out a little instead of clumping it all together?

In this video there is a POI that was never implemented, where might this have been @r4z0R49? https://m.youtube.com/watch?v=64slpzkb9Rc

Am I the only one who thinks this should be removed Or relocated? Please let me know, because it would be good to let the devs know if some map balance would need consideration.
