### ISSUE TITLE
super patches

### ISSUE THREAD

**Issue by tramper1111** [DayZMod/DayZ#46]
warum zum teufel wird das spiel immer mehr VERKACKT???? es kann doch nicht wahr sein. das spiel lief mal ordentlich. und mittlerweile kommen die server auf gar nicths mehr klar. hauptsache 1000 spieler, 11800000 helis und 234689204+ autos. SUPER!!! und nicht zu vergessen die 3 mio neuen waffen und ich kann mir jetzt sogar aussuchen was für n müll ich fresse, während ich ne packung nägel, klopapier und rasierklingen einsammel, während ich von nem zombie durch DIE VERSCHISSENE WAND umgeboxt werde. klasse. LEUTE MERKT IHR GAR NICHTS MEHR???? passt auf, ich erklär euch das ganze schritt für schritt: als erstes, streicht ihr mal dieses super tolle umhau feature. ist an sich nicht schlecht, aber es wäre erst angebracht, wenn die viecher nicht mehr durch die wand kommen können. als nächstes streicht ihr die ganzen neuen vehicel und waffen, und items und weiß der teufel was. dann macht ihr euch daran, die durchdiewandaction zu reparieren. UND PROBIERT ES VORHER AUS. und dann kümmert ihr euch um die stabilität an sich. es kann doch nicht sein, dass ich jetzt sogar bugs beim spawnen habe und sich das game aufhängt, bis ich einmal in der lobby wieder war oder sogar aufm desktop. und wenn das alles abgehakt ist, und das game besser und toller läuft, DANN, aber auch nur DANN könnt ihr anfangen irgend welchen müll ins game zu bringen. und jetzt kommt nicht mit: blabla, immerhin machen wir was, und das ist freiwillig und blaaaa. ich SCHEIß auf derartige patches, die durch freiwillige arbeit entstehen, wenn deren einziger zweck ist, das spiel noch mehr zu verbuggen. und wenn das ganze nicht möglich sein sollte, sprich ihr könnt nichts reparieren, sondern nur noch mehr müll einfügen, auf den die server nicht klar kommen, dann LASST ES SEIN. dann nehmt eure patches, spült sie im klo runter und lasst um himmels willen die finger davon!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dayz10k** [comment]
10/10 would read again!

**Comment by dayz10k** [comment]
yay google!

why the hell is the game more and more fucked up?? it can not be true. times the game ran properly. and now come the server on nicths even more clear. hauptsache 1000 player, 11800000 234 689 204 + cars and helis. SUPER! and do not forget the 3 million new weapons and even now I can choose what I n eat garbage while I ne nails packaging, toilet paper and razor blades einsammel while I'm vice-boxing of NEM shitty zombie by THE WALL. class. PEOPLE NOTES YOUR NOTHING MORE?? fits, I'll explain to you the whole step by step: first, stroking her super great Umhau times this feature. in itself is not bad, but it would only be appropriate if the critters can not get through the wall. next to her stroking the whole new vehicel and weapons, and items, and the devil knows what. then you make yourselves because the repair durchdiewandaction. AND TRIED IT OUT BEFORE. and then you care about the stability itself. it can not be but that I now even the bugs spawn and the game hangs in the lobby until I was once again encouraging or even desktop. and when this is all checked off, and the game runs better and great, THEN, but only THEN can you start to get into some garbage game. and now does not come with: blah, after all, what we do, and that is voluntary and blaaaa. I FUCK on such patches caused by voluntary work, if their sole purpose is to verbuggen the game even more. and if the whole should not be possible, ie you can not fix it, but only add more waste to which the server does not come clear, then LET IT BE. then take your patches, they flushed down the loo and let the finger to heaven sake of it!!!!!!!!!

**Comment by dayz10k** [comment]
I agree with you! this is my favorite feature:

 stroking her super great Umhau times

**Comment by R4Z0R49** [comment]
Find a real server not a modded version.

**Comment by Skaronator** [comment]
Ich hätte nie gedacht, dass die "Deutschen Kiddys" hier auf Github kommen.
Also auf einem Offizellen DayZ Server gibt es selten mehr als 60 Spieler und es gibt maximal 60 Fahrzeuge pro Server. Ich weiß nicht wieso du darauf kommst uns die Schuld zu geben was Admins auf ihren Eigenen Servern machen. Wir haben im Letzten Patch auch nur 2 neue Waffen eingefügt (MakarovSD, RPK) aber dafür auch wieder 2 Overpowerte Waffen rausgenommen (AS50, M107). Zu den Trashloot wie Klopapier oder Rasiereklingen: Das ist Trashloot und liegt ganz BEWUSST dort rum. In einer Zombie Apocalypse liegt doch nicht überall Gold und Essen auf den Boden ganz im gegenteil alles ist Zerstört und überall liegt Müll rum und das soll dieser neue Trashloot Simulieren. Es kommt doch viel Besser rüber wenn man unterschiedlichen Müll "findet" als wenn man jedes mal Leere Dosen sieht oder? Zu den Zombies: Wir versuchen das beste! Das ist ArmA - eine Militärsimulation und was wir daraus gemacht haben ist schon sehr gewaltig. Wir sind an der Grenze  des Machbaren in Arma und deshalb gibt es demnächst auch eine Standalone wo das Ganze Arma Zeugs rausfliegt.Wir Testen und Spielen unsere Patches auch selber bevor wir sie veröffentlichen aber es wir nie Perfekt sein! Du kannst es ja besser Programmieren und es uns zusenden aber ich vermute mal bei deiner Rechtschreibung kannst du es selbst nicht besser machen. (Wenn ich das jetzt mal so sagen Darf)
