### ISSUE TITLE
RESPAWN/WTF???

### ISSUE THREAD

**Issue by tramper1111** [DayZMod/DayZ#47]
bevor ichs vergesse: WESSEN IDEE WAR ES ZU KICKEN WENN MAN ES SCHAFFT DEN RESPAWN ZU BETÄTIGEN????? das kickt einen auch wenn man beinbruch hat und respawnen will. wieso ist der überhaupt aus? wär mal angebracht, das so zu bewerkstelligen, dass die server das entscheiden. weil auf reinen pvp servern rumkriechen bis man n zombie findet??? nö. und nochwas: SCHADENSMODELL. KEIN MENSCH, wirklich kein mensch wird BEWUSSTLOS wenn er 3 m in die tiefe fällt und auf den füßen landet. UND KEIN mensch überlebt es auch noch ohne beinbruch wenn er 30 Meter !!!!!!! in die tiefe fällt. ÜBERARBEITET MAL DAS!!!!!!!!!!!!!!!

**Comment by dayz10k** [comment]
Before I forget: WHOSE IDEA WAS IT TO KICKEN TO IT CREATES THE RESPAWN TO OPERATE?? the kicks even if you have a broken leg and will respawn. why is all of the above? Please consider appropriate times, manage to do so, the server decide. because rumkriechen on pure pvp servers until you find n zombie? nope and nochwas: DAMAGE MODEL. NO HUMAN BEING, not a human being really is UNCONSCIOUS when he falls into the 3 m deep and lands on his feet. AND NOT human it survived even without if he beinbruch 30 meters!!! falls into the deep. THE REVISED TIME!!!!!

**Comment by R4Z0R49** [comment]
Play on real servers not mode'd versions.
