### ISSUE TITLE
Pitching Tents

### ISSUE THREAD

**Issue by krazey** [DayZMod/DayZ#49]
Change:
if (r_action_count != 1) exitWith { cutText ["Wait for the previous action to complete to perform another!", "PLAIN DOWN"]; };

to:
if (r_action_count == 1) exitWith { cutText ["Wait for the previous action to complete to perform another!", "PLAIN DOWN"]; };
r_action_count = 1;

..and maybe add this betweeen "_location = _worldspace select 1;" and "//wait a bit" to remove ability to place tents on roads =)
//player on road
if (isOnRoad _location) exitWith { cutText ["You can not place Tents on a road.", "PLAIN DOWN"]; r_action_count = 0; };

**Comment by icomrade** [comment]
You are missing the point of this. It is set to "r_action_count"  + 1 every time you click the option. so it is reset to 0 at the end of the file (after a sleep period of 2 seconds i think). clicking twice would give r_action_count = 2.

So the reason it is != 1 is because if it's 0 you didn't click the option and if it's > 1 you clicked more than 1 time.

Is there a problem with this system? I don't know why you are posting this without an explanation.
