### ISSUE TITLE
Lifetime in Debug/journal

### ISSUE THREAD

**Issue by Landbergaren** [DayZMod/DayZ#511]
Hello. First of all I wanna thank you for doing a great job with patching the mod and helping it to come alive again! 

I think there is an issue with the journal or rather room for a nice improvement. Me who is a statistic-nerd with survivor-playstyle like to check the journal from time to time. It's all great except for the lifetime of your character. At the moment It displays how many days ago you created the character. Which basically do not mean much when it comes to accomplishment. What it should say instead is how long you have been alive online. How many hours online have this character survived. It should be doable I think since the servers know how long every character lived.

Cheers!

**Comment by VidKo** [comment]
I agree with Landbergaren. I made a character on official hive (when it was still up and running) and had a character that was 182 days alive and I maybe played about 5 hours on official hive.

**Comment by paradigmArchitect** [comment]
I would love this. People who play the survivor playstyle might be tempted to not play to keep their days alive high. Actually I know this happens because I've fallen victim to this type of thinking. Also if looking at peoples stats, often the accomplishment of being the longest surviving player goes to someone who didn't play a full minute in the game. The way it is now rewards people for not playing as far as survival time.

**Comment by Streatman** [comment]
IF this becomes a thing i would love to see the lifetime in the deathscreen

**Comment by R4Z0R49** [comment]
Done.
