### ISSUE TITLE
Can "Stash Medium ++++" be updated to add storage for Backpacks?

### ISSUE THREAD

**Issue by tiny11s** [DayZMod/DayZ#528]
As per title.

**Comment by R4Z0R49** [comment]
Stash's do not contain any backpack slots at all. I'm not sure id like to change this but ill talk with the others.

**Comment by tiny11s** [comment]
OK, just wondering as it seemed strange that they have a huge capacity but no Backpack slots like Tents.  Even if it was only 1 slot, would be useful.

**Comment by bchawke** [comment]
Just to weigh in, I think it would be great to have just one backpack slot in a fully upgraded stash.  To be honest, it's damn near impossible to hide a tent anywhere in Chenarus on a populated server (unless you glitch it into a rock/shed) due to their rendering distance (see issue #438 ).  Stashes are the only real way to hide things in DayZ mod.  Until the rendering distance of tents is altered it seems the only way to be able to stash a good backpack for later would be to have one slot available in a stash.
