### ISSUE TITLE
Request to use DayZ content and code in DayZ Epoch

### ISSUE THREAD

**Issue by vbawol** [DayZMod/DayZ#54]

**Comment by R4Z0R49** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are **only** allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by vbawol** [comment]
We are fine with this and would love to contribute anything of ours to the official mod.

**Comment by R4Z0R49** [comment]
K cool. i've added you guys so see you in 3 month :-)

**Comment by vbawol** [comment]
please renew this for another 3 months.

**Comment by R4Z0R49** [comment]
Done Thanks.
