### ISSUE TITLE
1.8.6.1 indestructible boats

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#552]
Hi!

I noticed that since the 1.8.6.1 patch was introduced, boats are indesrtuctable. I noticed that with the small boat and the fishing boat. Before the patch after a few shots they changed the appearance from new to damaged and after a few more shots they sank. In 1.8.6.1 they don't even change appearance after 2 full clips from a Mk48.

**Comment by R4Z0R49** [comment]
ill get this looked into for the next patch it must not be getting the damagehandler attached.

**Comment by vinyljunkie** [comment]
Did this get fixed? It causes a lot of teleport entries in the RPT from the player that's onboard while it sinks, instead of blowing up.

Line 8082: 2016-01-15 00:24:04 2/5:arma2oaserver: 0:24:02 "TELEPORT REVERT for player UID#XXX from [13746.5,5529.86,20.3139] to [0,0,51.6], 14817 meters, now at [0,0,51.6]"

Line 8083: 2016-01-15 00:24:04 1/2:arma2oaserver: 0:24:02 "TELEPORT REVERT for player UID#XXX from [13746.5,5529.86,20.3139] to [0,0,51.6], 14817 meters, now at [0,0,51.6]"

Line 8084: 2016-01-15 00:24:04 3/5:arma2oaserver: 0:24:03 "TELEPORT REVERT for player UID#XXX from [13746.5,5529.86,20.3139] to [0,0,51.6], 14817 meters, now at [0,0,51.6]"

Line 8085: 2016-01-15 00:24:04 2/2:arma2oaserver: 0:24:03 "TELEPORT REVERT for player UID#XXX from [13746.5,5529.86,20.3139] to [0,0,51.6], 14817 meters, now at [0,0,51.6]"

Line 8087: 2016-01-15 00:24:07 4/5:arma2oaserver: 0:24:03 "TELEPORT REVERT for player UID#XXX from [13746.5,5529.86,20.3139] to [0,0,51.6], 14817 meters, now at [0,0,51.6]"

Line 8088: 2016-01-15 00:24:07 1/2:arma2oaserver: 0:24:03 "TELEPORT REVERT for player UID#XXX from [13746.5,5529.86,20.3139] to [0,0,51.6], 14817 meters, now at [0,0,51.6]"
