### ISSUE TITLE
V1.8.7.dev1-Full Test Version

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#572]
Download - http://se1.dayz.nu/latest/.testsystem_1.8.7/@Client-V1.8.7.dev1-Full.rar

Client start Command = "%_STEAMPATH%\steam.exe" -applaunch 33930 "-mod=%_ARMA2PATH%;EXPANSION;ca;@Dayz-Dev;@DayZ-Chernarus" -nosplash -connect=108.174.57.160 -port=2305

Changes - https://forums.dayzgame.com/index.php?/topic/225520-dayz-mod-187/

Report issues here.

**Comment by R4Z0R49** [comment]
1st issue - Loot is not spawning. (Zeds need new loot table) - Utils updated but not passed to all scripts yet. (https://github.com/DayZMod/DayZ/commit/f067ecee781fca193933416cfdbebf3a847b2431)
2nd Issue - Loot Groups needs some tweaking.

**Comment by R4Z0R49** [comment]
Patch 1 - http://se1.dayz.nu/latest/.testsystem_1.8.7/@Dayz-Dev-1.8.7.Dev1.Patch1.rar

You must have @Client-V1.8.7.dev1-Full from the the frist post before adding this patch

**Comment by Lukethero** [comment]
Would be nice, not sure how easy of a fix this would be, but would it be possible to jack up the damage required to destroy walls and gates significantly to the point it is almost impossible without say, a satchel or two if at all? I know for a fact, at least on US 434 , that anybody who knows what they are doing is not making walls. All over the map are just countless failed bases, solely due to the fact that they kept getting broken. If it takes 10 minutes of hatcheting to bring down what might be an hours worth of wall. All these base glitching preventions mean nothing if nobody uses them. I would say either fix this now or just remove them from this build until you get this sorted out, because I gaurentee you, the only purpose it is serving right now is lagging the servers.

**Comment by thcNox** [comment]
"Other objects like tents will no longer be able to be placed in rocks and stones again."
Is this still a thing? I heard it was scrapped but it is still in the change list referenced here which makes me worry.

**Comment by R4Z0R49** [comment]
Stop worrying and test ?
