### ISSUE TITLE
Achievements to be Removed

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#574]
As topic says.

**Comment by skigoggles** [comment]
I know most of them are silly, but the steady aim, marksmen and sniper are useful to know you've gotten the kill during a battle.

**Comment by kichilron** [comment]
That is exactly not what they're intended for and thus why they're removed.

**Comment by Landbergaren** [comment]
Maybe the achievements should not be visible in front of the screen like they are now. They should have a page in the logbook instead. Then it requires some steps to confirm the kill. 

But ye the achievements without logs become a bit silly since you die a lot and start all over. You lose track of them and there are no hardcore-achievements. Just basic ones that you get in the start of your character that you get every life. 

My vote goes towards either removing them or reworking them a bit since I usually like achievements.

**Comment by Jbird206** [comment]
thank god
