### ISSUE TITLE
Request to use / utilise DayZ 1.7.6.1 code and content in DayZ Overwatch

### ISSUE THREAD

**Issue by scrumbee** [DayZMod/DayZ#60]
I would like permission to use the dayz mod code in new mod, I do understand to only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets. I will also include all DayZ Credits and recreate a new issue post every 3 month requesting continued use.

**Comment by thevisad** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by R4Z0R49** [comment]
Could you also include the mod name your using

**Comment by scrumbee** [comment]
im fine with all of that, Name of the mod is Dayz Overwatch

**Comment by R4Z0R49** [comment]
k added Thanks
