### ISSUE TITLE
Is all base building being removed?

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#606]
I saw some one-liners and comments and such and it sounds like all of it is being removed for 1.8.7. I'd like to vehemently disagree. While it may be a bit glitchy, I think its good enough - a few walls and a gate is fine. On my server we've seen a resurgence of of small clans and base building with no complaints other than when they try and find a padlock.

**Comment by Lukethero** [comment]
After further review, I think I would not mind it staying in. I tried breaking into a base the other day which had max level walls, and it takes a satchel and about 20 minutes of hatcheting. The problem is when multiple people are involved. Me and 2 other guys tried hatcheting through a fully leveled gate and it took 10 minutes max. That is the part that is the problem I believe.

**Comment by ericandersen** [comment]
![After Further Review](http://cdn.meme.am/instances/500x/66338672.jpg)

**Comment by Lukethero** [comment]
Agreed, server admins should have the choice.

**Comment by skigoggles** [comment]
funny, I don't think the players on my server have discovered the hatchet effectiveness.  Hoping that tweaking the hatchet vs gate damage code isn't hard. Point me in the right direction and I'll take a look at it.

**Comment by R4Z0R49** [comment]
The ability to build new bases will be removed in the next patch. While we work out a few issues.

Issues range from placing objects down too abuse of the base building system.
