### ISSUE TITLE
Request to use / utilise DayZ 1.7.7 code and content in DayZ Revolution

### ISSUE THREAD

**Issue by Vilemouse** [DayZMod/DayZ#62]
Requesting permission to use 1.7.7 code and future versions in DayZ Revolution: The rise and downfall of Civilization.

**Comment by Skaronator** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by Vilemouse** [comment]
Im fine with that thank you

**Comment by Skaronator** [comment]
k i've added you so see you in 3 month :-)
