### ISSUE TITLE
[Request] Earplugs or pilot headset item

### ISSUE THREAD

**Issue by ebayShopper** [DayZMod/DayZ#625]

**Comment by R4Z0R49** [comment]
Id probably just add a simple action or quick key to silence the rudder. then on player exit of vehicle reset the fade.

**Comment by Lukethero** [comment]
Yeah, me and my mates have been wanting this for a long time. Also cars can be bad sometimes, so maybe throw that int here as well.

**Comment by ebaydayz** [comment]
Requiring a magazine or item for it would be slightly more realistic. But a simple volume toggle hotkey is more convenient. Either way is good.

Samatra's KoTH and Wasteland on Arma 3 use F1 as the volume toggle hotkey. It just shows a muted speaker icon in the top right of the screen while active. I like the idea of automatically disabling it when exiting a vehicle too. If you want something simple like that I can submit a pull request for it.

**Comment by R4Z0R49** [comment]
go for it m8

**Comment by R4Z0R49** [comment]
Any info on this?

**Comment by ebaydayz** [comment]
I made a basic implementation of it:
https://github.com/EpochModTeam/DayZ-Epoch/commit/ab7254a121fe25d94bfbbe132dc283a061f45ce0

I didn't commit it here yet because you said:
> Do it on getin and getout
> R4Z0R49 - 05/01/2016
> But really just edit all the configs for each of the vehicles and lower the volumes
> No need for the ui icon
> Just run the fade when a player enters/exits any vehicle

The way I have it is the same as it is on A3 Wasteland and KoTH currently. The only difference is I added the automatic disable when exiting a vehicle. 

Unfortunately the fadeSound command mutes all in-game sound effects including gun shots, other vehicles, etc. AFAIK there is no command to only mute specific vehicle parts (like rotor or engine). So as it is currently you do not want it automatically applied when entering a vehicle. There are many times when you need to hear in-game sound effects at full volume.

Lowering vehicle sounds in the configs is an option, but that would be a lot of work balancing it for each vehicle. And there would probably be some people crying that those vehicles are supposed to be loud and forcing lower volume on them is unrealistic.

**Comment by KPanicEKS** [comment]
Just a little feedback.. If someone was going to put on ear protection in
real life then all noises would be lowered and not just the vehicle sounds.
There are some a3 mods that do it very well. Essentially you can toggle the
earplugs on or off. I don't know if we have limitations on the a2 side of
things but if we can emulate the way exile does it that would be great.

**Comment by ebaydayz** [comment]
Yes @M0tzilla the way I have it above is the same as it is done in most A3 mods including Exile. All sound effects are muted when it is active. That is why it should not be automatically applied when entering a vehicle as @R4Z0R49 suggested IMO, but instead toggleable by the player.

**Comment by KPanicEKS** [comment]
Ah yes. I just redhead your original post. Sorry for the confusion and
thanks for the clarification. I think that's a great addition. But will we
have to find them as a something to be added to our toolbelt or will
everyone have them by default?

**Comment by ebaydayz** [comment]
The way I have it above is just a hotkey you can use at anytime. It does not require an item, but it could be easily made to if people want that, as I suggested [in the OP](https://github.com/DayZMod/DayZ/issues/625#issue-138705527).

**Comment by R4Z0R49** [comment]
My comment was more a discussion rather then a command.

R4Z0R49 commented on Mar 7
go for it m8

**Comment by ebaydayz** [comment]
Okay. If @AlexAFlorov or someone wants to contribute an icon that fits better with the current UI we can use that instead. I'm not too skilled with image manipulation, so atm it is just the generic speaker icon seen here:
![20160430211306_1](https://cloud.githubusercontent.com/assets/7761693/14939563/3d581878-0f1a-11e6-9cd4-aae70b4e6adb.jpg)

White is probably a good color, because it stands out on the current UI. It's easy to forget you have it enabled without a noticeable icon.

**Comment by R4Z0R49** [comment]
If the icon is always on ie dimmed when not enabled then add the background if it just shows when enabled dont worry about the background.

Just my thoughts

**Comment by AlexAFlorov** [comment]
it is not needed to  be shown all-time ... only if enabled imo

i'll ask Tugodoomer to make icon for that

**Comment by AlexAFlorov** [comment]
[headphones.zip](https://github.com/DayZMod/DayZ/files/373343/headphones.zip)
@ebaydayz try that one... 

and use default background to keep current dayzui style :)

**Comment by ebaydayz** [comment]
Thanks Tugodoomer and @AlexAFlorov your icon is much better. This is what it looks like now:

![earplugs](https://cloud.githubusercontent.com/assets/7761693/17000207/71fdd16c-4e8f-11e6-8b41-572016fd9c5b.jpg)

When disabled it hides both the icon and background. It looks good with and without the background, so idk which is better. It's probably best to keep it for consistent style with the ear and eye above it. 

Committed here https://github.com/DayZMod/DayZ/commit/b5b743927e7ec01109bdd531aea5301adf881b17. If there is anything that should be changed let me know.

**Comment by AlexAFlorov** [comment]
It will be better to see with background on white/bright screen

maybe icon must be little smaller to fit current background?  

@ebaydayz what do you think?

**Comment by ebaydayz** [comment]
The size looks ok to me. Maybe it hangs off the background a little bit, but it doesn't have to fit exactly. The knife in the food icon hangs off too. 

It's up to you guys though. You may want to try it in-game at a few different resolutions and interface sizes to get a closer look.

**Comment by oiad** [comment]
Looks great to me. Is it worth putting it sequentially after the vision/sound icons or do you want a definite distinction?

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AlexAFlorov** [comment]
@ebaydayz 

[headphones_smaller.zip](https://github.com/DayZMod/DayZ/files/374999/headphones_smaller.zip)

smaller version of icons

**Comment by KPanicEKS** [comment]
Not sure if this is an engine limitation or not, but it would be very nice
to have the ability to disable sidechat on the client side for the servers
that have sidechat enable. Some servers get very chatty and the blue text
is very distracting not to mention the immaturity and meta gaming that
comes from having it on.

**Comment by ebaydayz** [comment]
Here it is using the smaller icon and aligned with the ear and eye:

![earplugs2](https://cloud.githubusercontent.com/assets/7761693/17025859/d064eba4-4f2b-11e6-8a8c-1c50d91ee769.jpg)

If @AlexAFlorov and everyone likes this I will go ahead and commit the change.

**Comment by KPanicEKS** [comment]
Looks great!

**Comment by AlexAFlorov** [comment]
:+1:
