### ISSUE TITLE
cz550 : invalid ammunition

### ISSUE THREAD

**Issue by elDoudou** [DayZMod/DayZ#632]
Currently, cz550 can't be used anymore because the 5Rnd_17HMR ammo is not recognized.

**Comment by AsFoxy** [comment]
Can you elaborate?

**Comment by elDoudou** [comment]
Having a cz550 sniper rifle in my inventory, as well as the required ammunitions (5x2).
But the ammo is not recognized and the sniper rifle can't load.

**Comment by wriley** [comment]
@elDoudou Is this related to #641?

**Comment by skigoggles** [comment]
My guess is that you didn't wipe the Db and the classname for CZ ammo and other weapons/ammo (mosin for sure) changed in 187.
There is a fixit script that foxy and I worked on - it was posted on the discord channel. Not sure if its here.

**Comment by elDoudou** [comment]
Indeed why should Database be wiped to accommodate a non functional change ?
May be that script shipped in next upgrade version ?

**Comment by R4Z0R49** [comment]
It was shipped to the discord channel due to us losing access to the forums. This is the first time in 3 years we have asked for admins to clean there db. Normally we try to updated the class-names from within the scripts inside the mod but this time we had so many class-names changes it wasn't possible.

The idea is so we can get move accurate feedback on the new loot system. 

3 Years isnt too bad for an alpha game.
