### ISSUE TITLE
Request to use / utilise DayZ 1.7.7.1 code and content in DayZ: Namalsk

### ISSUE THREAD

**Issue by SumrakDZN** [DayZMod/DayZ#64]
I would like to have permission to use DayZMod code in my project DayZ: Namalsk (http://www.nightstalkers.cz/en_index_dn.php?menu=en_dn_popis).

**Comment by Skaronator** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by SumrakDZN** [comment]
I am fine with that, thanks!

**Comment by Skaronator** [comment]
k, ty
