### ISSUE TITLE
ChemLight, Flare issue with reloading weapons.

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#641]
We seem to have an issue with reloading while carrying clemlights and flares.

Waiting on more info.

**Comment by vinyljunkie** [comment]
Spawning in and had flares in my inventory, picked up a Lee Enfield. Pressed R to reload it, nothing happened. Dropped  the flares and I was able to reload it. Picked up the flares and same issue, Lee Enfield unable to reload. Server restarted, logged back in and no problems with Lee Enfield reloading even though flares was in inventory or not.

**Comment by R4Z0R49** [comment]
i wonder if the same happens for picked up flares.

**Comment by R4Z0R49** [comment]
looking for a exact step by step to recreate. using QF13

**Comment by ebaydayz** [comment]
1. Spawn in as a new character. Flare will be in your inventory since it is a guaranteed respawn mag. 
2. Pick up any normal primary rifle like an Enfield or Winchester. 
3. Log out to lobby.
4. Log back in.
5. Fire a few rounds and then try to reload your partially full mag.

You can also reproduce by changing clothes with your primary out. https://github.com/DayZMod/DayZ/commit/0f767374b1de7a8444bfd091dc3dd92eebfaf94b does fix the problem on initial login. But relogging causes it to resurface. 

I also tested adding it back [where it was before in player_humanityMorph](https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/compile/player_humanityMorph.sqf#L89). That didn't help. Lastly I tried adding it at the bottom of player_switchModel (which should run on relog), but still no luck.

BTW, simply doing a `player removeWeapon "Throw";` right above the add will fix the duplicate weapon RPT error.

**Comment by R4Z0R49** [comment]
I was able to pickup weapons and reload while holding flares. Can someone confirm plz?

**Comment by ebaydayz** [comment]
With all the latest changes including https://github.com/DayZMod/DayZ/commit/7f7d3e02e786b0a2fee9cb9af1353f5b28a9eda6 applied I still get the issue on relog reproducible via the steps I listed above. 

Note after logging back in the currently selected weapon is flares even though the primary was selected when logging out. Then I am unable to reload my partially full mag after hitting ' F ' (default key) to select primary and firing a few rounds.

**Comment by R4Z0R49** [comment]
Ok I'm not sure what's going on just now I'm not getting this issue. I can reload after picking up new weapons even on logout. My primary weapon remains what it was before I logout and on login i can still reload.

**Comment by R4Z0R49** [comment]
Ok tested.

new spawn,
Picked up weapon,
Able to reload,
logged,
able to reload,
changed clothes,
able to reload,

Please let me know if you still have this issue.

**Comment by ebaydayz** [comment]
Confirmed fixed using latest Throw.hpp. 

Also confirmed it's no longer necessary to addWeapon "Throw" in player_monitor.fsm or player_humanityMorph. "Throw" is included in respawnWeapons in the main unit config, so it will always be a duplicate if readded:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgVehicles/Skins.hpp#L75

I briefly tested the other throw weapons like chem light, hand grenade, smokes, empty tin can, whiskey bottle, etc. and didn't notice any obvious issues from the Throw.hpp changes.

**Comment by R4Z0R49** [comment]
this should now be resolved.
