### ISSUE TITLE
[BUG] Fishing poles no longer spawn at docks - 1.8.7

### ISSUE THREAD

**Issue by KPanicEKS** [DayZMod/DayZ#656]
I have checked 5 separate times at the docks for fishing poles and noticed that no loot appears to be spawning at this building now. The building in question is "**Land_Nav_Boathouse**".

**Comment by Lukethero** [comment]
Did you check under the floor, they either spawn underground or floating I believe.

**Comment by KPanicEKS** [comment]
yeah, that's where they usually spawn. no loot is being spawned there in
this patch though, not even cans.

**Comment by rvett** [comment]
I have found loot there in 1.8.7, but it's very rare. Loot spawn chance is 10%, and 10% again that it's a fishing rod. On average you will thus have to check it one hundred times.

But I agree that this is a bit much.

**Comment by KPanicEKS** [comment]
I have a character on skaliski so I'll keep trying and document my efforts,
but thus far nothing. Also a  1% chance of spawning a fishing pole at the
docks seems excessive. Can we perhaps get a craftable pole
(wood+6 string+razor blade+nails), would give the razor blade a use which
is junk loot at the moment. Maybe the craftable pole would have a chance of
breaking similar to the hatchet when used.

**Comment by R4Z0R49** [comment]
Crafted fishing pole might be a good idea.

**Comment by KPanicEKS** [comment]
any reason on why the loot rate changed so drastically on this building from 1.8.6? I've now tried 14 times to loot it on separate occasions and still have not found a single item above or below it.

**Comment by rvett** [comment]
Sorry, my bad, I thought you meant the "boat at the docks" rather than the "boat house". (Did you edit your OP to write that you mean Land_Nav_Boathouse?) Anyway, the small boat at the docks has a loot chance of 10%, the boat house has none in 1.8.7., so it defaults to zero, which is probably a bug. This explains why you never found anything there.

So, @R4Z0R49 : Land_Nav_Boathouse needs a lootChance.

I would also love to be able to craft a fishing pole btw! Suggestion: Wood pile + 3 strings + scrap metal + some can of food = fishing pole.

**Comment by KPanicEKS** [comment]
Thanks for confirming, I thought I was taking crazy pills for a min.

**Comment by R4Z0R49** [comment]
0e20239d0f3104a20454ddce5fa2e61e762e1dc6
