### ISSUE TITLE
Antibiotics infinite when given to somebody

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#670]
Antibiotics infinite when given to somebody. Only decrease if taken by itself.

**Comment by R4Z0R49** [comment]
Antibiotics have a random consumed system. This will be updated in the next patch to always consume one tablet.

**Comment by Lukethero** [comment]
It is not random when you scroll wheel on a player and choose give antibiotics. It does not consume a tablet 100% of the time.

**Comment by Inurosen** [comment]
@R4Z0R49 
This is not fixed.
File `dayz_code\compile\fn_damageActions.sqf`

``` sqf
_action = _unit addAction [localize "str_actions_medical_give_antibiotics", "\z\addons\dayz_code\medical\antibiotics.sqf",[_unit], 0, true, true];
```

There is no item passed to `antibiotics.sqf`, `_unit` only, thus `_medsUsed = _this select 1;` in `dayz_code\medical\antibiotics.sqf` is  `Nil`, which is passed to `dayz_reduceItems` function.

Since there is nothing to reduce one's antibiotics stay untouched. I can pull request the fix if you want.

**Comment by R4Z0R49** [comment]
This is indeed an issue thanks inursen for digging it out.

Thanks
