### ISSUE TITLE
Crossbow Quiver

### ISSUE THREAD

**Issue by Tibsun** [DayZMod/DayZ#677]
If you fill the a quiver with an arrow, it will create a full new quiver not combatible with your crossbow you just have shot. Same trying to make new quiver with that arrow you have found or shot, it is not combatible.

**Comment by R4Z0R49** [comment]
Ill check this out. 

Thanks.

**Comment by icomrade** [comment]
I noticed that the wrong class is still in the following file: https://github.com/DayZMod/DayZ/blob/d955ee68746b736c43a9ac96272f8ced03063836/SQF/dayz_server/compile/fa_hiveMaintenance.sqf#L133

**Comment by R4Z0R49** [comment]
If i'm not mistaken its a fnc we no longer use.

**Comment by ebaydayz** [comment]
Correct, most of the functions in that file are not used at all anymore. I was going to remove them along with some more unused code which is still compiling (and in some cases running) unnecessarily. But I didn't want to spam the vanilla commit history too much since 2.0 is going to wipe it all anyway. 

We can go ahead and take out the unused stuff in Epoch though @icomrade. I already removed some of it. I'll do it here too if you are okay with it @R4Z0R49.

**Comment by R4Z0R49** [comment]
Yea, go for it 2.0 is a full rewrite so i'm not so worried about the commit history here too much.

The main goal is just finish some of the ideas and get the balance running as much as we can before 2.0 hits do any cleanup we need before hand for other mods using the base. But i am back at work i only have the weekends to do anything. I have the automated build system up and running so shout if you need a test build running in-between the weekends. David has already said he can push to steam without much worry during the week. I just need to finish the stable build system for steam.

Thanks
