### ISSUE TITLE
Request to use DayZ 1.7.6.1 content and code in DayZ X / DayZ Extra

### ISSUE THREAD

**Issue by Rickpla** [DayZMod/DayZ#68]
I would like to have permission to use DayZMod code in my project DayZ X.

**Comment by Skaronator** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by Rickpla** [comment]
I'm fine with that thank you!

**Comment by Skaronator** [comment]
k, ty
