### ISSUE TITLE
[Request] Give us the ability to see who has killed another fellow player

### ISSUE THREAD

**Issue by DATGUY321** [DayZMod/DayZ#681]
I would like to say that all the changes that have been made are working just fine, the only aspect that has bothered me and a few other people trying to be a hero is the fact that we cant identify who is an open target (players we are allowed to shoot without losing humanity).

I found myself in a situation today where i witnessed a male survivor kill a female survivor, so i killed the male only to see hero skin turn back to a normal survivor skin. There is no possible way for us to see who we can kill and who we cant based just on "oh i saw this man kill some1" because the same thing might happen.

A possible solution for this would be to simply make a survivor or hero become marked once the commit a murder, like make their clothes bloody or take their hat away, all in all just make it possible for players to identify who is a ''survivor'' and who is a ''bandit in a survivor clothes'' and allow us to defend ourself properly.

**Comment by Lukethero** [comment]
Agreed, this is a good idea.

**Comment by rvett** [comment]
The open target system is meant for self defense, not retaliation or street justice. Like in a real life situation, when you witness a killing between two strangers, you cannot tell who is the bad guy, because you don't know their history. This is how it works now, and how it's supposed to be in my opinion.

You're asking to be able to defend yourself properly. This is already the case. When a survivor or hero shoots at you or your teammate who you now is a good guy, you can be sure he's become an open target, and you can return fire. In any other situation you should not be able to tell who's free to kill (except for bandits of course).

**Comment by R4Z0R49** [comment]
Yea, i think the system in atm is pretty good we dont wont to hightlight who has done what outside of the initial humanity system.

Thanks
