### ISSUE TITLE
Request to use / utilise DayZ 1.7.7.1 code and content in DayZ Infection

### ISSUE THREAD

**Issue by SmokiesStash** [DayZMod/DayZ#74]
Would like to ask permission to use the dayz code in a new mod i am working for.

all requirements will be followed and all authors/credits cited

thank you for your time looking at this request

**Comment by Skaronator** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are **only** allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply. And could you also include the mod name your using?

**Comment by SmokiesStash** [comment]
Completely fine will all said requirements.

DayZ: Infection is the Mod

Mod name is not set in stone yet and i hope that isnt an issue.
Once i Verify the name isnt taken i will be purchasing a domain.

**Comment by R4Z0R49** [comment]
No worry's just update us with the name when you have it set in stone.

Thanks

**Comment by SmokiesStash** [comment]
Updating and Requesting to use the new 1.8 dayz code in the mod ive been working on, DayZ:LIFE is the mod name and it is set in stone. Weve decided to go a different route then before.

Thank you for taking the time to look at this request and also thanks again for allowing me to use the 1.7.7.1 code
