### ISSUE TITLE
Request: Revert pain effects the old style

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#786]
It seems that a vast majority of new players do not understand the slow swaying animation when they're in pain.  They do not connect it with pain and end up posting in side chat or on Discord asking how to fix the gun sway.  The older pain effects with the violent shaking and desaturation were easily associated with pain by new players and they made much more sense.  People would immediately try taking painkiller when the effect happened.  I think having it be an intermittent effect rather than constant is a good idea, but using the rapid shaking and desaturation would help players identify the problem better.

The slow sway works well for dehydration in my opinion and should be kept for that purpose.

**Comment by AndrewEscocia** [comment]
I still see the the violent shaking from time to time, bug or ? 
I would also back the more violent shaking as it gives a use to pain killers, for me I never use em. Just wait for a few secs and the sway goes away.
Would a ui marker be unacceptable? sorta like the red and yellow chains or the broken bone icon.

**Comment by Borges1091** [comment]
@AndrewEscocia Current violent shaking occurs from blood being below 3000 or 5000. I forgot which. I think 3k.

Edit: It's 4500, which I think is too high anyways.

**Comment by bchawke** [comment]
Yes, Borges is correct, the violent shaking happens currently when you're on critical low blood.  I forget the exact number, 2.5-3k sounds about right.

**Comment by Landbergaren** [comment]
You also shake violent when you are freeziing. 

But what made people understand before was specially the UI icon that poped up and said you where in shock. 
This topic has been discussed before and most of us agreed on that maybe there should be a signific painsound instead to keep the UI clean. Perhaps the default Arma 2 inpain sound. Razor mentioned it has to be the same sound for both genders apparently :s. Atm there is a breath sound together with pain. But basically noone have noticed it so its not doing its job.
I think the gunsway is good and it have gotten some good feedback from others as well. With a noticeable sound it would be quite perfect. That way pain also affects pvp in orientation just like cough can make enemy's find you easier.

**Comment by devguy91** [comment]
I think the confusion is largely caused by the swaying effect happening quite abruptly and randomly, at least for myself, therefore, there is not much correlation with the causation of pain inflicted a few minutes earlier and the animation. Also, the swaying animation and the flux of saturation doesn't necessarily relate to pain or blood and is is frankly quite annoying and sort of motion sickening. I've seen players in the chat thinking the swaying was an inspect weapon animation like in CS:GO, and for many it seems more like fatigue/thirst or a game bug.
I would personally like to change or revert the pain and blood mechanics to something which makes more sense, like the proportional decrease in saturation with blood which I thought was a really smart feature, and a more correspondent and differentiable pain animation like the original shaking, if one at all (maybe only an audio queue since I really dislike the swaying).

Note: I haven't played the game in a while so sorry if I have gotten some facts wrong, but the point remains the same.
