### ISSUE TITLE
Servername In Mission Generator - ServerName

### ISSUE THREAD

**Issue by Muppet1856** [DayZMod/DayZ#8]
Entering server name (ex. US1234 and instance number 9876) results in the file having this:
//dayZ_serverName="UK9876"; // server name (country code + server number)

Commented and not right.  References the Instance number and the wrong country - and commented out.

**Comment by fgw-** [comment]
can confirm this: name is set wrong.

fortunately the instance number is set correctly (as specified) in init.sqf.

**Comment by icomrade** [comment]
Confirmed. The Country code is always UK, it's bugged. However, it may be intentionally commented out, just edit manually until it's fixed.

**Comment by Muppet1856** [comment]
Why is this closed?  If it is a bug - you track it and close it when its fixed.  This is not.  Please re-open.

**Comment by MattzFiber** [comment]
Whats the point of having millions of issues open? Thats why we have prority lists.  To track the reported issue. An issue is closed when its been added to the list and its fixed quite quickly

**Comment by Silentspy** [comment]
Should work correctly now though, apparently i forgot that since i first created this small script it replaced 1337 and just that no matter where it was, and that UK1337 was the default servername so it got replaced 2 places at once instead of properly replacing instance id line instead and just that

the script is now just a few lines with the recent optimizations i did and should work perfectly fine now!

if someone still have issues, always feel free to contact me so i can further investigate.
