### ISSUE TITLE
Request to use DayZ 1.7.7.1 content and code in DayZ Escape

### ISSUE THREAD

**Issue by Andrew-S90** [DayZMod/DayZ#82]
I would like to get permissions to go ahead with my mod officially and be able to use new DayZ Code. My idea is DayZ Escape, message me on skype andrew_s9010 to talk or any info needed.

Andrew

**Comment by sharkiller** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by Andrew-S90** [comment]
All sounds good from here.
Let me know if further info is needed

**Comment by sharkiller** [comment]
then is ok
