### ISSUE TITLE
[request] balancing the game

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#821]
Some requests for balancing the game

1) backbags - larger than 8 slot backbags could found only from military loots (barracks)
2) CZ rifle with zoom level 2 only (makes difference between other rifles)
3) food spawns (canned foods & drinks) only in supermarkets
4) remove all choppers and replace them with civilian airplanes - invading bases & looting helicrashes is then much more difficult
5) atleast 30% chance to find attachments (acog, cco etc.) from military loots (barracks, tents) - guns aren't in such a big role as attachments to them, if it's "almost sure" to find pso, acog or cco for example from barracks it would draw more people there
and my personal favorite 6) make crossbow ultimate weapon, damage bigger than any other gun (for example 12 000 damage head/chest shot)

Also would like to see more infection, like 30% chance to get infected from each zombie hit. Curing infection is way too easy nowadays so it's not basically any threat at the moment.

**Comment by Borges1091** [comment]
Not sure if trolling..if not, here's my opinion on each of your requests.

1. Anything above 8 slot backpacks in barracks? What? There are 6 barracks in the entire map. No one should be forced to run to the most dangerous areas to find a 12 slot backpack. Residential packs are fine. Maybe alice packs should be made rarer.
2. Seems okay since there's on difference between CZ and other high end military bolt snipers.
3. Seeing how there are like 5 supermarkets in the entire map, and the current nutrition rates it would make more sense to play the game instead of playing supermarket simulator. Would break the game hard.
4. Lol.
5. Could use more attachment spawns.
6. No one hit chest kill weapon should be in the mod regardless of what it is. Current has 5533 base damage which is pretty good, and explosive bolts kill in one shot and disable vehicles/damage bases (or will). Could up the base damage by 1-2k though.

30% chance of infection is a terrible idea. Reasons why are antibiotics are still extremely rare to find in hospitals. Viral zeds drop them yes but it's hit or miss you could kill 500 without finding 1 or find 2 in 30. Seems like best way to cure infection is owning a tent. High infection chance was in a previous patch and I remember it was so game breaking bad that I just stopped playing until it was fixed. Reason was you were constantly getting infected and going to hospitals yielded nothing 90% of the time so you just ended up killing yourself everytime.

**Comment by B73** [comment]
1... 8 slot backbag is enough for keep food and drinks. Want more space (for weapons) - go looting dangerous areas.
3... hunt/go fishing. Several ways to get food. Easy way = supermarket, more time consuming = hunt/fish
4... choppers raid bases constantly, also too easy to fly from helicrash to another. With plane it needs skill/time.
6... crossbow is useless nowadays. Could you kill someone with it from 100 metres? With highest damage of all weapons it would be something to look for.

And infection.. you can cure yourself with herbal drink / tent. Antibiotics are really common too. Nothing to fear if infection strikes, just way too many ways to cure it. Remove resting and herbal drinks then it would be more ok.

**Comment by Borges1091** [comment]
1. They shouldn't be just restricted to dangerous military areas, it's too limiting. Going for highest risk for a 12 slot backpack isn't really ideal.
3. Have you looked for fishing poles? They're rarer than nvg, and only limited to coast.
4. Heli's are part of what make dayz mod awesome.
6. Crossbow could use a damage buff to around 7-8k damage. It's supposed to be a close range weapon with a ~50 meter range. Herbal drink infection cure chance is very low, and is useless in most situations. So is using other peoples tents. It's cut to -50%. If you have your own tent the % is fairly good. Gives players more incentive to use tents too.

**Comment by bchawke** [comment]
Wow, it kinda *does* seem like a troll post.  Most of the things you're asking for are insanely radical changes that would drastically alter gameplay.  That's not "balancing", that's redesigning the game.  I'd recommend creating your own derivative mod like DayZero and DayZ 2017 did if you want to alter the game that much.

1) Backpacks: Backpack meta works well now, and there's already been lengthy discussion on making the Alice pack more rare and increasing the British pack's slots by two

2) CZ scope: this is the only really reasonable suggestion.  I'm for it 100%

3) Food spawns:  I personally was a fan of the patches where canned food and drink did very little at all and you were pretty much required to hunt and find fresh water.  Thing is, it became too difficult for a) new players and b) casual players.  Limiting food spawns to supermarkets only is too challenging and completely unrealistic (you don't think you'd find a can of food in a house or cabin in the woods?)  Also, in regards to hunting, animal spawns become more sparse when the server has more players on it.  It may seem like a petting zoo when you play on a partially full server, but we've been in scenarios with full pop where we've had trouble finding so much as a pig or a goat when we need one.  Personally I think the balance is good now.  Canned food/drink could use a bit of a nerf in my opinion but it's still much better than it was back in pre 1.8.1.

4) Chopper removal: this is pretty ridiculous.  Choppers are a staple of the mod and the amount of resources and work that it takes to get one running and keep it running with fuel is just right.  There are other ways of mitigating heli crews from sweeping heli crashes that I've suggested in other issues here that don't require something so drastic as removing choppers.  As for base raiding, it's not that hard to build bases that are immune to heli raids.  Avoid level 7 platforms in the rooms with tents/stashes.  Make tent/stash rooms too small for the heli to pick a player back up.  Use cargo nets.  Most servers have rules against going into a base you cannot get out of and logging there as well as using tents to send loot through walls.  With these rules in place and smart base building you can keep your stuff safe from helis.

5) 30% chance is way too high, but I have suggested increasing attachment spawns at barracks.  Barracks are virtually useless now as the only 4 reasons to go are 1) satchel charges (which are so insanely rare that I haven't seen one yet since 1.8.7 dropped something like 10 months ago), 2) backpacks (which are so rare that you have much better chances of killing a player and taking his, so why bother?), 3) LMGs that nobody really uses or cares about, and 4) attachments which, again, are so rare that it's not worth the trouble or time to go to the barracks.  If the rate was raised to 30% every single player carried assault rifle you come across would be fully built.  It's good that a fully built assault rifle is a rare find.

6) Crossbow: one shot kill is too far.  This isn't Half-Life or CoD.  An arrow shouldn't do the same amount of damage as a .50 cal rifle round.  I think there are other ways to make it more valuable.  I'd like to see the crossbow fit in the melee slot, but not sure if that's possible.

Infection: I'd rather see a reduction in antibiotics spawns so people relied more heavily on making herbal drinks and resting at tents.
