### ISSUE TITLE
Alive duration (Build 189)

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#849]
Alive Timer needs resetting after model change.

**Comment by R4Z0R49** [comment]
https://cdn.discordapp.com/attachments/118428354906030082/309419961762185216/20170503210220_1.jpg

10 secs between these screenshots

https://cdn.discordapp.com/attachments/118428354906030082/309419971769794560/20170503210356_1.jpg

**Comment by R4Z0R49** [comment]
Zikk - Yesterday at 9:09 PM
1. Logged in.
2. Checked DB - @ 340 duration.
3. Press ESC to bring up menu
4. Checked DB - @ 441 duration.
5. Closed menu and opened it again.
6. Checked DB - @ 441 duration.

so it feels like its triggered by the first time the Abort countdown is shown.
db is updated directly once you bring up the menu but not the in-game journal.

**Comment by R4Z0R49** [comment]
"524 + 0 = (524)"
6 mins later
"524 + 6 = (530)"

Time in game reported as 8h40m give or take

**Comment by R4Z0R49** [comment]
Login, http://i.imgur.com/QQhFl6r.jpg
Waited 10 seconds with abort menu, http://i.imgur.com/JHDBi99.jpg
Loaded Journal again, http://i.imgur.com/PsJ0oKD.jpg

**Comment by nsonP** [comment]
So, i did a few more tests.
To get a baseline i wrote down some basic good-to-know information.

**Database:** Fresh install with 1.8.9 SQL files _(from 2017-05-01)_
**Server started:** 2017-05-04 00:13:58
**Current time:** 2017-05-04 20:05 _(when I started testing)_

**Start duration for character:** 572
**Character last_updated:** 2017-05-30 22:39:33

----

**Test 1** 
Login, check duration in Journal and DB once the game is fully loaded.
_Result:_
Journal: 0 Day(s), 9 Hour(s), 32 Minute(s)
Database: 572
[http://imgur.com/JMu2Bil](url)

**Test 2**
Terminate the Arma 2 OA process and check the DB.
_Result:_
Journal: N/A
Database: `1174`
[http://imgur.com/QlkZfhx](url)

**Test 3**
Restart server. Login and check duration in Journal and DB.
_Result:_
Journal: 0 Day(s), 19 Hour(s), 34 Minute(s)
Database: 1174
[http://imgur.com/fBu4o0K](url)

**Test 4**
Press the ESC key to bring up the menu. Check duration in DB.
_Result:_
Journal: 0 Day(s), 19 Hour(s), 38 Minute(s)
Database: 1179
[http://imgur.com/oaCKyP1](url)

**Test 5**
Wait a few minutes then terminate the Arma 2 OA process and check the DB.
_Result:_
Journal: N/A
Database: 1197
[http://imgur.com/hQMwOV4](url)

**Test 6**
Log back in. Press the ESC key to bring up the menu. Check duration in DB.
_Result:_
Journal: 0 Day(s), 19 Hour(s), 58 Minute(s)
Database: 1199
[http://imgur.com/HrfZC51](url)


**Conclusion** (?)
It is possible to recreate the problem. However, it does not seem to have anything to do with the actual menu showing up. Since I found the issue when just terminating the Arma 2 OA process.

Right now it feels like a server uptime issue. To test this i will leave the server running for a few hours and then test the same thing again.

**Comment by R4Z0R49** [comment]
Ok ill have another look at the db side see if i can see an issue.

**Comment by R4Z0R49** [comment]
Note ziks server was running 24 hours this is likly to be the issue as time events in the way arma handles time get widly inaccurate

**Comment by nsonP** [comment]
And that is shown between T2 - T3. After restart the issue is gone.
_(guess i will have to activate the automated server restarts again)_

Even if this issue turns out to be a false positive it's good to know about what happens if you don't use the recommended 3h restart cycle.

**Comment by R4Z0R49** [comment]
Fixed Closing for now till the next test.

**Comment by R4Z0R49** [comment]
Reopening issue, Comments cleaned from original problem.
