### ISSUE TITLE
Missing Cherno Docks fire barrel

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#869]
I'm sure many have noticed this before, but I haven't found this documented anywhere. Oil barrels are invisible sometimes. Seems pretty random, and happens only with oil barrels.

![oil_barrel_invisible](https://user-images.githubusercontent.com/6949874/27658821-97dbdb2e-5c51-11e7-88c8-61dee75f47f6.jpg)

I have been observing this for quite a long time now -- it's not a 1.8.9-related issue, so I'm posting this separately here.

**Comment by R4Z0R49** [comment]
ok thanks.

**Comment by ebayShopper** [comment]
Was this a modified server that disabled the town generator (junk in the roads) or a vanilla server? Could you post the coordinates of one of them that is missing next time you encounter it? Thanks.

**Comment by rvett** [comment]
This is vanilla, the screenshot was taken yesterday on US434 in front of the church in Cherno.

Next time it happens I'll play around with my graphics settings to see if that has any effect. I wonder if this is related to #257 ...

**Comment by thcNox** [comment]
I believe US434 has indeed played around with town generator. I believe I recall reading they thought the roads were too cluttered etc.

**Comment by rvett** [comment]
I asked, and they told me they tried a custom town generator for a week some months ago, but since then used the original one from vanilla. So that can't be it.

**Comment by rvett** [comment]
Alright, I've just checked this on Europa, U434 and A Dead Man Walking. The barrel is missing on all three servers. It's actually the one at the Cherno docks bus stop, not in front of the church, sorry about that. And it's not just invisible, it's actually not there (i.e., no collision, you can just walk right through where it should be).

This seems to be the offending line in CfgTownGeneratorDefault.hpp:

`class Object1 { type = "Land_Fire_barrel"; position[] = {6847.45, 2360.25, 0}; direction = 0; onFire = 0; };`

Not sure if this is the only one though.

**Comment by ebayShopper** [comment]
The flames spawn separately from the barrels because they are separate objects.
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_server/system/lit_fireplaces.sqf

But you are correct, this particular barrel is not spawning:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgTownGenerator/CfgTownGeneratorDefault.hpp#L1042

I checked other fire barrels in the town generator and they spawn fine. I also checked other items that were first (index zero and one) and last in each town generator array and they all spawn. My guess is this exact spot happens to fall outside of a grid or something. @facoptere's code is difficult to follow, but you can see all the checks that happen before a town generator object is spawned here:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/system/scheduler/sched_towngenerator.sqf

**Comment by rvett** [comment]
Thanks for clarifying. As a simple fix I would suggest to just remove both objects (barrel & fire), as there are plenty of other barrels in Cherno. (Why none in Elektro, btw?)

**Comment by ebayShopper** [comment]
Ok, removed for now. Please reopen this and leave a comment with coordinates if you find any other missing town generator objects.
