### ISSUE TITLE
Dissembling walls without an eTool

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#932]
1) I can dissemble a wall down to a single level frame, then I get an error that the "" is missing.  (should say eTool)
2) Not sure of the intended dynamic - should I be able todo this without an eTool (I have a toolbox)
4) While the wall is visually down to the frame, the db does not reflect that (still says WoodenFence_7)
3)  Once I have an eTool, it does fully dissemble, but no materials are returned.

![20180112131935_1](https://user-images.githubusercontent.com/13056467/34891698-6f973124-f7a4-11e7-9813-57c72eef971b.jpg)
![20180112131959_1](https://user-images.githubusercontent.com/13056467/34891701-722a333c-f7a4-11e7-856f-b7875fa5929e.jpg)
![20180112132653_1](https://user-images.githubusercontent.com/13056467/34891704-73c83c34-f7a4-11e7-968c-33b15f00a27c.jpg)

**Comment by skigoggles** [comment]
ok, materials returned are random.

**Comment by ebayShopper** [comment]
The message is fixed with 11e3607.

Correct me if I am wrong @R4Z0R49, but it looks like he intended you to only need an Etool once you get to the frame level. Level 1-7 only require a toolbox to disassemble to the previous level. See:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_buildings/configs/woodenFence.hpp#L51

The original is deleted in the database on the first successful loop here:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/actions/object_disassembly.sqf#L72

And then the new one is published at the end of the script if the deletion was successful:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/actions/object_disassembly.sqf#L150

You need to refresh your database to see the change. If you are using HeidiSQL click at the very top on the server name (not database name) and hit F5.
