### ISSUE TITLE
Please revert changes made to Huey gunner view.

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#934]
In 1.9.0 @Streatman made changes to the gunner view on the Huey. I would like this change reverted to it's previous state as I  do not consider it an improvement but rather has many negative effects such as not being able to zoom in due to the gun obscuring the target. Streatman suggested not zooming in as some sort of "work around" but I'm not buying it. Frankly I view this change as not only being unnecessary but actually having significant negative impact on the Huey guns.

**Comment by VidKo** [comment]
I agree. It's was hard to hit anything from the huey before, now it's even harder. The ring obscures too much view and you can't aim ahead anymore.

**Comment by R4Z0R49** [comment]
ok ty, Ill leave open for other comments as well.

**Comment by thcNox** [comment]
Streatman argues this is for the sake of realism and "immersion". Gameplay and game balance are apparently taking a back seat on this one.  Regardless I argue that this new change is anything but realistic. 

Heli gunners do not aim by lining up their iron sights on target. This would be near impossible to do in a moving vehicle. Instead hey align their head with the gun and aim alongside the top of the barrel and use tracers to correct their aim. 

Below is a picture of the original gun view. This quite accurately simulates looking over the barrel rather than through iron sights.

![20180119114002_11](https://user-images.githubusercontent.com/10793000/35167071-63654a34-fd54-11e7-94a2-956774d69b7e.jpg)

Next you have the current & "improved" gun sights:
![20180119114002_1](https://user-images.githubusercontent.com/10793000/35167142-a61bb1ce-fd54-11e7-8bd8-4a7997e52244.jpg)

Note that this is not zoomed in. it gets even worse when zoomed in.

More of an anecdotal reference: https://www.youtube.com/watch?v=I_4cH_5Zl-c&feature=youtu.be&t=213 

Note how these gunners are not lowering the heads to look through the iron sights but rather looks above the gun barrel.

**Comment by Landbergaren** [comment]
since both of you want immersion and accurate simulations I suggest that you aim like before 1.9 but the iron sight is not perfectly zeroed in with magic.  Shooting where the iron sight points should make you shoot above your target. So you would have to aim below your target to actually hit. This way it would simulate pretty good how it works irl and everyone gets their immersion. 

Also "it being hard to hit before" is not the games fault since it shot exactly where you pointed due to hardly any recoil. with almost all rng removed it was up to pilot and gunner to have the skills.. If they did they would kill the target so fast that it did not even make sense. If you missed it was simply due to error from the heli-crew. Against a good heli crew with only one contact pinned down... Target peak = target dies.

**Comment by thcNox** [comment]
I'm not the one clinging to the argument that's it's for the sake of immersion. Also I think where the iron sight is zeroed is less important. Unless you are completely dead still in the air the  the iron sights acts as a mere point of reference as is demonstrated in this video: https://www.youtube.com/watch?v=unbEzXGCu8Y
You need to heavily lead your targets and at this point iron sights are just a reference point to start shooting. You use the traces to get on target. What's more important is having a clear view of your target and where your tracers are going. This the reason gunners are not trying to track to track targets through a peephole but rather over  the barrel.

**Comment by Landbergaren** [comment]
What you just wrote was an argument to change it to what I just suggested though.
Since my suggestion supports the alignment you do in a real chopper. As you say you have the barrel point as a reference and then you use your gut-feel and calibrating skills.. Not a perspective that pre 1.9 was actually halfway past the barrel (magic) to give you a unrealistic forgiving experience that is merely a huge buff that the Huey do not really need. 

If everyone wants the game to be unrealistically forgiving just for the sake of more people repairing hueys then I guess a complete revert is the best choice. But for how it actually should work it does not make sense pre 1.9. Streatman have some good images of pre 1.9 pov when aiming ^^. It was really stupid.

**Comment by thcNox** [comment]
Pre 1.9 camera wasn't half way past the barrel. It may appear that way due to foreshortening brought on by the zoomed view. 
![20180119165429_2](https://user-images.githubusercontent.com/10793000/35170263-e397b92a-fd5f-11e7-8609-a7a4f31b5230.jpg)

The Pre 1.9 camera is pretty accurate and close to what you would see looking over the barrel in real life if you take into account that the game has considerably narrower field of view which again is made worse by the zoomed in view. With the risk of being called a troll I must confess I do not fully understand your problem with the original view other than you think it's magic that it appears to be too far down the barrel.  Also it seems you have moved away from standing on the argument that it's for realism/immersion and now you are saying that the huey was too powerful and needed to be taken down a peg? 

There are a lot of hardcore mil sim groups that are very capable of making the changes they want and have done so yet they haven't messed with m240 sights from what I 've seen but for some reason this was a very important issue in DayZ of all places.

**Comment by Landbergaren** [comment]
_"Also it seems you have moved away from standing on the argument that it's for realism/immersion and now you are saying that the huey was too powerful and needed to be taken down a peg?"_ 

Im not sure what your point is here. Those are two different arguments supporting the same setting. 

_"The Pre 1.9 camera is pretty accurate and close to what you would see looking over the barrel in real life "
"Pre 1.9 camera wasn't half way past the barrel. It may appear that way due to foreshortening brought on by the zoomed view."_

Then please explain why bullets fly in the same direction as how your POV align with the ironsight. Is the barrel shooting downwards from where its actually pointing? 

![35170263-e397b92a-fd5f-11e7-8609-a7a4f31b5230](https://user-images.githubusercontent.com/12958109/35171429-0e9b8788-fd64-11e7-9209-a86f92607dd3.jpg)

Remember, I'm referring to both of you talking about "how it should be", "immersion", "realism". And if that was what you actually cared about then my suggestion makes more sense. But I understand that people don't want it as hardcore as I would want it. 
But lets keep it real. You don't care about the immersion. You care about how easy you think it should be to kill someone with the huey and you got really upset that its a bit harder in 1.9. And I understand. Its a videogame after all and your way of thinking is not necessarily stupid. But lets keep it real and post the real reasons so we can move on :). We are both adults here.

**Comment by Streatman** [comment]
i can show you how the original Aimpoint is placed. If you want you can look it up yourself by Downloading and installing all needed programms and the sample models of arma 2 if you dont believe me.
![before edited](https://user-images.githubusercontent.com/24512691/35172160-cf30fcba-fd66-11e7-9def-60713de88aa6.png)

**Comment by Inurosen** [comment]
My players mostly don't like it. I personally don't have any problems with it tho.

**Comment by Landbergaren** [comment]
I would love if it is like now when mouse2. But when you would have normal view you would still align the gun with the direction you are looking but now above the gun with the POV at where the head would be at. 
But I guess that would require some scripting to make it work properly. 

And then have a more forgiving mode as server-setting with having it as how it was before where you have a very forgiving POV where you can use ironsight and still have the benefits of free sight with POV placed halfway past the gun.

**Comment by Streatman** [comment]
i can make it that the aimpoint is further away then it is now, so the ring gets smaller and covers less.

**Comment by thcNox** [comment]
I stand corrected in regards to the camera position, though it's not half way down the barrel, more like 30% either way fact remains that it's a close approximation to view a real gunner would have.

 If it's a bit further down the barrel or if the bullets are more aligned with the player view rather then gun (a very slight difference in angle) I'd consider it fair compensation for the camera being in fixed in place unlike a real gunners head and having a very narrow field of view compared to a real human eye.

>  But lets keep it real. You don't care about the immersion. You care about how easy you think it should be to kill someone with the huey and you got really upset that its a bit harder in 1.9. And I understand. Its a videogame after all and your way of thinking is not necessarily stupid. But lets keep it real and post the real reasons so we can move on :). We are both adults here.

I've never voiced any reasons for my opinion other than the new camera view doesn't make any sense at all. I bring up realism and immersion because those were the stated reasons for the change when I asked why it had been changed. I then outlined above my argument for why I think that's moronic.  

Now however it seems this is more about you guys having issues with Hueys being too over powered more than anything else. You both seem to agree that it's about making the huey guns harder to use and yet the change long entry says "...and gunner seat now have improved visibility in first person view." Pretty funny.

Again I'm requesting the gunner view to be reverted to vanilla as I see no reason to mess with the original view. If you have a personal opinion on how the choppers should be re-balanced you could start a conversation on that but if they do need to be re-balanced I'm sure this moronic change to the gunner view  is not the best way to go about it.

**Comment by Streatman** [comment]
i never said that i did it for balancing i did it because i think the vanilla sight is ugly.
if you want to "guess" where your bullets land like your pictures are suggesting i suggest you just use the middle of your screen, because it doesnt matter if you have a croshair turned on or of, the aim is always in the mittle of the screen. i will try to get you a video that someone can very well shoot with this sight and hit stuff with it.
i also think that your picture is a realy bad example, who knows what weapon technologie this soldier is using. he might have a HuD in his helmet that aims for him.
when you get a picture of the exact huey with this exact gun without any additions then you might have a valid point, but not with pictures like this.

**Comment by Landbergaren** [comment]
The hueys were not overpowered just because the perspective was messed up. Just like the hueys are not OP because they get up to 200 free m240-bullets added each restart. 
But that should not stop you from fixing the issues.

**Comment by thcNox** [comment]
Did get some footage today: https://www.youtube.com/watch?v=WR-Kd4Y4oHw
I think it demonstrates that the gun is always in the way and if you want to hit something you have to basically line it up so the rim of the peep hole is covering the target. the last clip shows how easily you lose the target because the gun cover so much of the screen. 

Regardless @R4Z0R49 seem to have no issues with having this "improved" view being available as an "opt in" feature. That way you can leave the gunner view the same way it's been the past 9-10 years for vanilla and if you want to have your own setting on your server that would be your business.

**Comment by Landbergaren** [comment]
This is the view when pressing minus on numpad and it will stay zoomed out even when toggling viewmode back n forth. If Streatman manages to push the default pov back a decimeter, then it would be really sweet, then you can zoom back even more if prefered. But vision is good like this. But ye push back default a bit since a lot of people forget or dont really know about all the mechanics in this game.
![20180120191158_1](https://user-images.githubusercontent.com/12958109/35186640-7f680852-fe17-11e7-86cb-ad8984795f4c.jpg)

**Comment by thcNox** [comment]
Problem is you can't zoom and use the gun. You want to zoom out even further as some sort of solution?

Leave vanilla alone and you can set up the hardcore version however you like.

**Comment by R4Z0R49** [comment]
Might just be best to create two models one with the new system one with the old admins can then choose whats best for there own server.

**Comment by Streatman** [comment]
@R4Z0R49 Both models exist. you can just use the Vanilla model i guess and the one i created for that
