### ISSUE TITLE
Request To Use DayZ Mod 1.8, All Credits Will Be Given And Left For DayZ Special Ops

### ISSUE THREAD

**Issue by DeejayCrazy** [DayZMod/DayZ#94]
Hey Guys, I would like to request permission to use the DayZ Mod 1.8 Files for use with my new WIP mod called DayZ Special Ops, That we are currently looking to work on using the latest files, I will provide all credits as posted in the licence file located here https://github.com/DayZMod/DayZ/wiki/License-and-permission-to-use

Thank You,
xDeejayCrazyx @ [DayZSO]

**Comment by Skaronator** [comment]
You must include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You are only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by DeejayCrazy** [comment]
I agree to the above post.

xDeejayCrazyx

**Comment by Skaronator** [comment]
k, ty
